/* tests/js/test_sound_bus_editor.mjs — MASTER / SEND FX use the SAME editor as
 * track FX (Josh, 2026-09-02: "master/send effects should use the same editor
 * as track effects").
 *
 * The gap he reported from the device: a Master FX effect had no **Module** and
 * no **My Presets** pages. They were never missing functionality — they are
 * generated by the stock param-pages editor's `trailingMenus`, and bus inserts
 * were excluded from that editor by `ppApplies()`'s `!S.bus` term, so they fell
 * to davebox's older bank-model editor where the same doors hide behind a
 * jog-click instead of sitting at the end of the jog walk. Upstream never wired
 * Master FX for the grid either (it landed 2026-08-21, after this fork's
 * watermark), and it withholds the trailing menus there to this day — davebox's
 * own trailingMenus is component-agnostic and only had to be let through.
 *
 * Pinned here as the OUTCOME, not the boolean: a gate can be right while the
 * plan it produces is wrong. A global bus must PLAN the trailing pages; a MOVE
 * bus must still be excluded — a SCOPING choice (Josh ruled "master/send"), not
 * an impossibility: Move-bus FX inserts would plan fine, it is only Move's own
 * generator row that has nothing to plan from. */

let failed = 0;
function ok(label) { console.log(`  ok   — ${label}`); }
function bad(label, e) { console.error(`  FAIL — ${label}: ${e && e.stack ? e.stack : e}`); failed = 1; }
function step(label, fn) {
    /* ⚠⚠ An ASYNC fn returns a promise this runner never awaits: the body would
     * not run, nothing would throw, and the step would report ok. A test that
     * passes because it did NOTHING is worse than one that fails. Caught
     * 2026-08-24 — an async step "passed" against a mutation it could not have
     * seen. Hoist awaits to module scope; keep step bodies synchronous. */
    if (fn && fn.constructor && fn.constructor.name === 'AsyncFunction')
        throw new Error('step("' + label + '") got an ASYNC function — it would pass ' +
                        'without running. Hoist the awaits to module scope.');
    try { fn(); ok(label); } catch (e) { bad(label, e); }
}

/* ---- host surface ---- */

/* Every shadow_get_param that reaches us, so the round-trip COUNT is testable
 * — "is it cached" is a cost question and cost is the whole reason the reads
 * are deferred to tick in the first place. */
let reads = [];
const ASSIGN = {
    'knob_1_target': 'synth', 'knob_1_param': 'cutoff',
    'knob_3_target': 'fx2',   'knob_3_param': 'room_size',
    /* knob 5 is deliberately unassigned: both keys answer empty. */
    'synth:cutoff': '0.4830',
    'fx2:room_size': '0.75',
    /* A loaded synth, so a block can actually be opened and the VIEW_EDIT
     * exclusion tested against the real view rather than a forced one. */
    'synth:module': 'nusaw',
    /* ⭑ The metadata is the point of the movy law, so the fixtures are chosen
     * to break a naive implementation:
     *   cutoff    — declares a COARSE step (0.5 over a 0..1 range = two
     *               positions). Normalising outright is what recovers it.
     *   room_size — a WIDE range (0.5..20) with a fine step. Using the declared
     *               step here is what makes a knob crawl.
     *   voices    — an INT whose 1% of range is 0.07; the declared step must
     *               act as a FLOOR or it would never move.
     *   shape     — an ENUM, exempt from normalisation, fixed detents per step.
     */
    'synth:chain_params': JSON.stringify([
        { key: 'cutoff', name: 'Cutoff', type: 'float', min: 0, max: 1, step: 0.5 },
        { key: 'voices', name: 'Voices', type: 'int', min: 1, max: 8, step: 1 },
        { key: 'shape', name: 'Shape', type: 'enum', options: ['Saw', 'Square', 'Tri'] },
        { key: 'preset', name: 'Preset', type: 'int', min: 0, max: 99, step: 1 },
    ]),
    'fx2:chain_params': JSON.stringify([
        { key: 'room_size', name: 'Room Size', type: 'float', min: 0.5, max: 20, step: 0.01 },
    ]),
    'synth:voices': '4',
    'synth:shape': 'Saw',
};

/* Sound mode's view enum (ui_sound.mjs) — not exported, and not worth
 * exporting for a test; pinned here so a renumbering shows up as a failure. */
const VIEW_EDIT = 1, VIEW_KNOB_TARGET = 12, VIEW_KNOB_PARAM = 13;
globalThis.shadow_get_param = (slot, key) => { reads.push(key); return ASSIGN[key] || ''; };
/* Writes are the observable now that the value is owned in JS and written
 * absolutely. The stub also RECORDS the write back into ASSIGN, so a re-seed
 * reads what was actually set — a stub that always answers the original value
 * would make every re-touch look like a revert. */
let writes = [];
globalThis.shadow_set_param = (slot, key, val) => {
    writes.push({ key, val }); ASSIGN[key] = String(val); return 1;
};
let dspMidi = [];
globalThis.shadow_send_midi_to_dsp = (slot, msg) => { dspMidi.push(msg.slice()); };

/* Drawing surface. mvPrint/hdrPrint emit set_pixel per glyph pixel — the host
 * `print` stub never sees them (the mixer work paid for that lesson three
 * times), so text is measured as pixel bands, never as captured strings. */
let fills = [], px = [], seq = 0;
globalThis.fill_rect = (x, y, w, h, v) => { fills.push({ x, y, w, h, v, seq: seq++ }); };
globalThis.draw_rect = () => {};
/* ⚠ The REAL semantics, not a no-op: `stipple_rect` REMOVES half the ink of
 * whatever is already drawn, so a rig that counts pixels must see that happen
 * or its thresholds mean something different here than on the device. */
globalThis.stipple_rect = (x, y, w, h, value, phase) => {
    for (let yi = y; yi < y + h; yi++)
        for (let xi = (((x + yi) & 1) === ((phase || 0) & 1)) ? x : x + 1; xi < x + w; xi += 2)
            globalThis.set_pixel(xi, yi, value);
};
globalThis.set_pixel = (x, y) => { px.push({ x, y, seq: seq++ }); };
globalThis.clear_screen = () => { fills = []; px = []; seq = 0; };
globalThis.print = () => {};
globalThis.pixel_print = () => {};
globalThis.flush_display = () => {};
globalThis.text_width = (t) => String(t).length * 6;

/* ⚠⚠ TRIPWIRE: the entry-point wrapper swallows exceptions into seq8-jserr.log,
 * and a stubbed writer drops them — a tick that died on line one then looks
 * exactly like a clean pass. Fail the run instead. */
let swallowed = null;
const filesWritten = [];
globalThis.host_write_file = (path, body) => {
    if (String(path).indexOf('jserr') >= 0 && swallowed === null) swallowed = String(body).slice(0, 900);
    else filesWritten.push(String(path));
    return true;
};
for (const fn of ['host_read_file', 'host_file_exists', 'host_ensure_dir',
                  'host_remove_dir', 'host_system_cmd', 'host_module_set_param',
                  'host_module_get_param', 'host_send_midi', 'move_midi_inject_to_move',
                  'host_set_led', 'set_led', 'host_get_setting', 'host_set_setting',
                  'move_midi_internal_send', 'host_vol_block', 'host_edit_cc_block',
                  'host_ext_midi_remap_clear', 'host_ext_midi_remap_set',
                  'host_ext_midi_remap_enable'])
    globalThis[fn] = () => (fn.indexOf('read') >= 0 || fn.indexOf('get') >= 0 ? '' : 0);

async function main() {
const { stubParamPagesDevice } = await import('./stubs/param_pages_device.mjs');
stubParamPagesDevice();

const { S: GS } = await import('../../ui/ui_state.mjs');
const snd = await import('../../ui/ui_sound.mjs');

const cc    = (d1, d2) => snd.soundOnCC(d1, d2, (v) => (v < 64 ? v : v - 128));
const ticks = (n) => { for (let i = 0; i < n; i++) snd.soundTick(); };
const pp    = () => snd.soundPPForTest();

/* A loaded FX module on Master FX's first insert, described the way the planner
 * reads it: the controller asks `<prefix>:ui_hierarchy` / `chain_params`, and
 * the prefix on a bus is the full component key (`master_fx:fx1`). */
const BUS_FX = {
    'master_fx:fx1:module': 'rrverb',
    'master_fx:fx1:chain_params': JSON.stringify([
        { key: 'room_size', name: 'Room Size', type: 'float', min: 0.5, max: 20, step: 0.01 },
        { key: 'mix', name: 'Mix', type: 'float', min: 0, max: 1, step: 0.01 },
    ]),
    'master_fx:fx1:room_size': '4.0',
    'master_fx:fx1:mix': '0.35',
    /* A non-empty state, or saveUserPreset bails with 'NO STATE' before it ever
     * records the preset — the save path needs something to write. */
    'master_fx:fx1:state': '{"room_size":4,"mix":0.35}',
    /* ⚠ A real ui_hierarchy, not chain_params alone: the controller's
     * refreshTrailing() BAILS when it has no hierarchy ("nothing this component
     * declared to rebuild against"), so a chain_params-only fixture cannot
     * exercise the trailing-page rebuild at all — the test would report the bug
     * fixed or unfixed identically. Shape per docs/MODULES.md. */
    'master_fx:fx1:ui_hierarchy': JSON.stringify({
        levels: {
            root: {
                name: 'RRVerb',
                params: [
                    { key: 'room_size', name: 'Room Size', type: 'float', min: 0.5, max: 20 },
                    { key: 'mix', name: 'Mix', type: 'float', min: 0, max: 1 },
                ],
                knobs: ['room_size', 'mix'],
            },
        },
    }),
};
Object.assign(ASSIGN, BUS_FX);

function enterMasterFxBlock() {
    GS.sessionView = false;
    for (let i = 0; i < 8; i++) GS.trackRoute[i] = 0;
    GS.activeTrack = 2;
    snd.soundEnter(2, 2);
    ticks(3);
    snd.soundEnterBuses();
    cc(3, 127); cc(3, 0);          /* jog click -> into the bus (MASTER FX) */
    ticks(3);
    if (!snd.soundIsGlobal()) throw new Error('rig: not in a global bus context');
    cc(3, 127); cc(3, 0);          /* jog click -> open the FX 1 block */
    ticks(6);                       /* discovery + ppSync + the planner's reads */
}

step('⭐ a MASTER FX insert opens the param-pages editor, same as a track FX', () => {
    enterMasterFxBlock();
    const st = pp();
    if (!st.applies)
        throw new Error('ppApplies() still excludes a global bus — the !S.bus term is back');
    if (!st.on)
        throw new Error('the editor did not take the screen on a Master FX insert');
});

step('⭐ ...and it PLANS the trailing My Presets / Module pages', () => {
    /* The pages Josh reported missing. They come from ppIo().trailingMenus,
     * which is component-agnostic — it only ever needed the gate opened. */
    const names = [];
    let guard = 0;
    /* Walk the jog forward through the plan, collecting page names. The walk
     * clamps at the last page, so a repeat means we are at the end. */
    for (;;) {
        const p = pp().page;
        const n = p && p.name;
        if (n && names[names.length - 1] !== n) names.push(n);
        if (++guard > 40) throw new Error('the page walk did not terminate: ' + names.join(' / '));
        const before = n;
        cc(14, 1); ticks(2);
        const after = pp().page && pp().page.name;
        if (after === before) break;
    }
    if (names.length < 2)
        throw new Error('the plan has too few pages to judge: ' + names.join(' / '));
    if (!names.includes('My Presets'))
        throw new Error('no "My Presets" page on a Master FX insert — pages: ' + names.join(' / '));
    if (!names.includes('Module'))
        throw new Error('no "Module" page on a Master FX insert — pages: ' + names.join(' / '));
});

step('⚠ CONTROL: a MOVE bus is still excluded — scoping, not impossibility', () => {
    /* Without this, the step above would pass just as well against a gate that
     * had been removed outright rather than narrowed to session buses. */
    GS.sessionView = false;
    GS.trackChannel[3] = 1;
    GS.trackRoute[3] = 1;                  /* ROUTE_MOVE */
    GS.activeTrack = 3;
    snd.soundExit();
    snd.soundEnterMove(3);
    ticks(4);
    if (!snd.soundActive()) throw new Error('rig: sound mode did not open on the Move track');
    /* ⚠⚠ ASSERT THE OTHER TERMS FIRST. `!applies` alone is not a control — it is
     * true for six different reasons, and this step only reaches the gate
     * because S.moduleId happens to survive soundExit() (only soundRetarget and
     * runDiscovery ever clear it). Add the obvious hygiene of clearing it on
     * exit and this step would pass against a BROKEN gate. So require every
     * term except busOk to be true, and the gate is then the only thing left
     * that can decide. */
    const t = pp().terms;
    for (const [name, v] of Object.entries(t)) {
        if (name === 'busOk') continue;
        if (!v) throw new Error('control is VACUOUS: term "' + name + '" is false, so the ' +
                                'busOk gate is not what decides this step');
    }
    if (t.busOk)
        throw new Error('a MOVE bus was let into the param-pages editor — the gate was ' +
                        'removed outright instead of narrowed to session buses');
    if (pp().applies)
        throw new Error('ppApplies() is true on a Move bus');
});

step('⭐⭐ SAVE AS from the grid actually SAVES — pendingAction must drain while the editor is up', () => {
    /* Josh, from the device: "user presets don't seem to be saving."
     *
     * startSaveFlow() queues `{t:'usrsavedo'}` on S.pendingAction and the
     * keyboard's confirm returns to the grid. But soundTick's `if (ppOn) {…
     * return; }` sits ABOVE the pendingAction drain, and that block rescues
     * only the baked scan and the write ledger — so with the grid up the action
     * is stranded forever: the keyboard takes the name, closes, and NOTHING
     * happens. No file, no error message.
     *
     * ⚠ NOT a bus bug — the grid has owned track FX since it shipped, so this
     * broke Save As everywhere. The bus change only widened where it bites.
     *
     * Pinned at the mechanism (an action queued under the grid gets consumed),
     * because that is the thing that was silently untrue. */
    enterMasterFxBlock();
    if (!pp().on) throw new Error('rig: the grid is not up, so this proves nothing');
    writes.length = 0;
    snd.soundQueueActionForTest({ t: 'usrsavedo', name: 'AdvisorTest' });
    ticks(6);
    if (snd.soundPendingActionForTest())
        throw new Error('the action is STILL queued after 6 ticks — stranded behind the ' +
                        'ppOn early-return, which is why Save As writes nothing');
});

step('⭐ SAVE AS updates the shown preset NAME — the page must rebuild, not just the record', () => {
    /* Josh, 2026-09-02: "the name of the current preset doesn't update after you
     * do a save as." Save As is the ONLY preset action that lands via
     * pendingAction (the keyboard defers it), and it was the only one not
     * followed by ppRefreshPresets — up_save and up_delete both call it inline.
     * saveUserPreset DID set the record; nothing rebuilt the trailing page that
     * displays it, so the row kept the old name.
     *
     * Pinned at what the user SEES (the row's value), not at the record — the
     * record was already correct while the screen was wrong. */
    enterMasterFxBlock();
    if (!pp().on) throw new Error('rig: the grid is not up');
    const NAME = 'AdvisorTake';
    snd.soundQueueActionForTest({ t: 'usrsavedo', name: NAME });
    ticks(6);
    if (snd.soundPendingActionForTest()) throw new Error('the save action never drained');

    /* Walk to the My Presets page and read its Preset row. */
    let found = null, guard = 0;
    for (;;) {
        const p = pp().page;
        if (p && p.name === 'My Presets') { found = p; break; }
        if (++guard > 40) break;
        const before = p && p.name;
        cc(14, 1); ticks(2);
        if ((pp().page && pp().page.name) === before) break;
    }
    if (!found) throw new Error('rig: never reached the My Presets page');
    const rows = found.entries || found.items || [];
    const row = rows.find(r => r && (r.label === 'Preset'));
    if (!row) throw new Error('no Preset row on the My Presets page: ' + JSON.stringify(rows).slice(0, 200));
    if (String(row.value || '').indexOf(NAME) < 0)
        throw new Error('the Preset row still shows "' + row.value + '" after saving "' + NAME +
                        '" — the page was not rebuilt');
});

step('⭐⭐ a module SWAP from inside the grid re-runs DISCOVERY — or presets file under the OLD module', () => {
    /* The FOURTH thing stranded behind soundTick's `if (ppOn) { … return; }`.
     * applyModulePick sets pendingDiscover and returns to VIEW_EDIT; ppSync
     * re-enters the grid on the next tick, and the countdown below that early
     * return never decrements — so runDiscovery never runs and S.moduleId keeps
     * naming the module you swapped AWAY from.
     *
     * ⚠ This one does not merely do nothing, which is what makes it the worst
     * of the four: saveUserPreset builds its directory from S.moduleId, so
     * Save As writes the NEW module's state into the OLD module's preset folder
     * under its name. Silent, and only discovered later when the list is full of
     * presets that load into nothing sensible. */
    enterMasterFxBlock();
    if (!pp().on) throw new Error('rig: the grid is not up');
    if (snd.soundModuleIdForTest() !== 'rrverb')
        throw new Error('rig: expected rrverb, got ' + snd.soundModuleIdForTest());

    /* Swap the module underneath, exactly as applyModulePick leaves things. */
    ASSIGN['master_fx:fx1:module'] = 'cloudseed';
    ASSIGN['master_fx:fx1:chain_params'] = JSON.stringify([
        { key: 'size', name: 'Size', type: 'float', min: 0, max: 1, step: 0.01 },
    ]);
    ASSIGN['master_fx:fx1:ui_hierarchy'] = JSON.stringify({
        levels: { root: { name: 'CloudSeed',
                          params: [{ key: 'size', name: 'Size', type: 'float', min: 0, max: 1 }],
                          knobs: ['size'] } },
    });
    snd.soundQueueDiscoverForTest(6);
    ticks(10);

    if (snd.soundModuleIdForTest() !== 'cloudseed')
        throw new Error('discovery never ran: the editor still believes "' +
                        snd.soundModuleIdForTest() + '" is loaded — Save As would file the new ' +
                        "module's sound under it");
    /* The editor must come BACK, re-planned for the new module — dropping it
     * without ppSync re-entering would trade one bug for a blank screen. */
    if (!pp().on)
        throw new Error('the editor did not re-enter after the swap');
    /* ⭑ And the PLAN must be the new module's, not just the id. The controller
     * re-plans only on an `is_loading` falling edge, which a module that does
     * not implement it never gives — so without dropping the editor the grid
     * keeps showing the OLD module's knobs, writing to keys that no longer
     * exist. The page's `keys` is the discriminator. */
    const planKeys = (pp().page && pp().page.keys) || [];
    if (planKeys.indexOf('size') < 0 || planKeys.indexOf('room_size') >= 0)
        throw new Error('the grid still shows the OLD plan after the swap: ' +
                        JSON.stringify(planKeys));

    /* ⭑ AND THE DAMAGE ITSELF: a save now must land in the NEW module's folder.
     * This is what the user actually loses — the id assertion above is the
     * mechanism, this is the consequence. */
    filesWritten.length = 0;
    snd.soundQueueActionForTest({ t: 'usrsavedo', name: 'AfterSwap' });
    ticks(6);
    const preset = filesWritten.find(f => f.indexOf('/presets/') >= 0);
    if (!preset) throw new Error('the save wrote no preset file at all: ' + JSON.stringify(filesWritten));
    if (preset.indexOf('/cloudseed/') < 0)
        throw new Error('the preset was filed under the WRONG module: ' + preset);
});

if (swallowed !== null) { console.error('  FAIL — a SWALLOWED exception reached the jserr log:\n' + swallowed); failed = 1; }
process.exit(failed);
}
main();
