/* tests/js/test_widget_pixels.mjs — the 2026-08-29 widget style-port: PIXELS
 * ON, BEHAVIOUR OFF.
 *
 * ⚠⚠ THE TWO FAILURES THIS PINS, and both are silent:
 *
 *   1. A NEW LOOK LEAKING ONTO AN OLD SCREEN. Every widget added here is
 *      opt-in through a descriptor field or a viz flag, and davebox sets none
 *      of them today. If one of them ever starts drawing by default, every
 *      bank page in the app changes at once and nothing else in the suite
 *      notices — the manual renders are regenerated by hand, and the page bar
 *      blinks off Date.now() so a careless PNG diff is noise either way. So
 *      the assertions here are equality against the SAME draw with the field
 *      absent, not "does it look right".
 *
 *   2. A "NOTHING TO SHOW" READ DRAWING A PICTURE. The sample track must draw
 *      literally nothing with no peaks and no markers, and the knob ring must
 *      answer colour 0 — not the bottom of its ramp — for an unbound knob.
 *      Both are the same rule (a read that produced no answer must not produce
 *      a confident output) and both have cost upstream a device report.
 */

let failed = 0;
const ok = (l) => console.log(`  ok   — ${l}`);
const bad = (l, e) => { console.error(`  FAIL — ${l}: ${e && e.stack ? e.stack : e}`); failed = 1; };
function step(label, fn) {
    if (fn && fn.constructor && fn.constructor.name === 'AsyncFunction')
        throw new Error('step("' + label + '") got an ASYNC function — it would pass without running.');
    try { fn(); ok(label); } catch (e) { bad(label, e); }
}
const assert = (c, m) => { if (!c) throw new Error(m); };

const W = 128, H = 64;
let fb = new Uint8Array(W * H);
globalThis.set_pixel = (x, y, v) => { x |= 0; y |= 0; if (x >= 0 && x < W && y >= 0 && y < H) fb[y * W + x] = v ? 1 : 0; };
globalThis.fill_rect = (x, y, w, h, v) => { for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) globalThis.set_pixel(x + i, y + j, v); };
globalThis.draw_rect = (x, y, w, h, v) => {
    globalThis.fill_rect(x, y, w, 1, v); globalThis.fill_rect(x, y + h - 1, w, 1, v);
    globalThis.fill_rect(x, y, 1, h, v); globalThis.fill_rect(x + w - 1, y, 1, h, v);
};
globalThis.stipple_rect = () => {};
globalThis.clear_screen = () => { fb.fill(0); };
globalThis.print = () => {};
globalThis.text_width = (t) => String(t).length * 6;

/* ⭑ THE CLOCK IS FROZEN. A time-dependent renderer makes two renders of the
 * same page differ by when they ran, which would make every before/after
 * equality here flap. drawKitPageBar blinks at ~1.3 Hz and the latch frame
 * animates. */
const FROZEN = 1756400000000;
Date.now = () => FROZEN;

const shot = (fn) => { fb = new Uint8Array(W * H); fn(); return fb.slice(); };
const same = (a, b) => { if (a.length !== b.length) return false; for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false; return true; };
const ink = (a) => { let n = 0; for (let i = 0; i < a.length; i++) if (a[i]) n++; return n; };

async function main() {
const kit = await import('../../ui/ui_movy.mjs');
const cells = await import('../../ui/ui_cells.mjs');
const rings = await import('../../ui/ui_knob_leds.mjs');

const arc = (label, norm, extra) =>
    Object.assign({ kind: 'arc', label, name: label, text: String(norm), norm }, extra || {});
const PAGE = [arc('A', 0.2), arc('B', 0.5), arc('C', 0.8), arc('D', 0.35),
              arc('E', 0.6), arc('F', 0.1), arc('G', 0.9), arc('H', 0.45)];
const draw = (cs, opts) => kit.drawKitBankPage(cs, Object.assign(
    { headerText: 'TEST', pageIdx: 1, pageCount: 4, touchedIdx: -1 }, opts || {}));

/* ---------------------------------------------------- 1. modulation dot */

step('a cell with no modNorm draws exactly what it drew before the port', () => {
    const plain = shot(() => draw(PAGE));
    /* An explicitly-absent field must be indistinguishable from the field never
     * having existed — null, undefined and a non-finite number all mean "no
     * source", and each of them has a different truthiness. */
    for (const v of [undefined, null, NaN, '']) {
        const withField = shot(() => draw(PAGE.map((c) => Object.assign({}, c, { modNorm: v }))));
        assert(same(plain, withField), 'modNorm=' + String(v) + ' changed the page');
    }
});

step('the dot adds ink, and adds it at a DIFFERENT place for a different value', () => {
    const a = shot(() => draw(PAGE.map((c, i) => (i === 0 ? Object.assign({}, c, { modNorm: 0.9 }) : c))));
    const b = shot(() => draw(PAGE.map((c, i) => (i === 0 ? Object.assign({}, c, { modNorm: 0.1 }) : c))));
    const plain = shot(() => draw(PAGE));
    assert(ink(a) > ink(plain), 'modNorm drew nothing');
    assert(!same(a, b), 'the dot did not move with its value');
});

step('the dot is drawn even where it COINCIDES with the pointer', () => {
    /* The mark's absence has to mean "nothing is modulating this". If a
     * coincident dot were skipped, a source resting on its base would read as
     * an unmodulated knob — which is the one reading it must never give. */
    const plain = shot(() => draw(PAGE));
    const coincident = shot(() =>
        draw(PAGE.map((c, i) => (i === 0 ? Object.assign({}, c, { modNorm: c.norm }) : c))));
    assert(!same(plain, coincident), 'a dot at the pointer value drew nothing');
});

step('the dot is a five-pixel plus, inside the ring, at every angle', () => {
    for (let i = 0; i <= 20; i++) {
        const n = i / 20;
        const only = shot(() => kit.drawModDotAt(64, 32, 7, n));
        assert(ink(only) === 5, 'dot at ' + n + ' is ' + ink(only) + ' pixels, not 5');
        /* Every lit pixel strictly inside the ring radius: an even-sized or
         * badly-placed mark straddles the circle and eats its silhouette. */
        for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
            if (!only[y * W + x]) continue;
            const d = Math.hypot(x - 64, y - 32);
            assert(d < 7, 'dot pixel at radius ' + d.toFixed(2) + ' touches or crosses the r=7 ring');
        }
    }
});

/* -------------------------------------------------- 2. filter fill + EQ */

step('the filter fill is the DEFAULT, and fill:false still escapes it', () => {
    /* Adopted 2026-08-29. The escape hatch is asserted as hard as the default,
     * because it is the only thing that lets a future caller ask for the bare
     * stroke — and an unexercised escape hatch is one that has already rotted. */
    const viz = { start: 0, cutoffNorm: 0.5, resoNorm: 0.4, mode: 'lp' };
    const dflt = shot(() => draw(PAGE, { filt: viz }));
    const on = shot(() => draw(PAGE, { filt: Object.assign({ fill: true }, viz) }));
    const off = shot(() => draw(PAGE, { filt: Object.assign({ fill: false }, viz) }));
    assert(same(dflt, on), 'the default is not the filled curve');
    assert(ink(dflt) > ink(off), 'the default drew no more mass than fill:false');
    /* ⚠ The fill must be UNDER the stroke: every pixel the bare stroke lights
     * is still lit with the mass on. Reversed, the checker punches its lattice
     * through the curve and the graph acquires holes exactly where it is being
     * read. That is invisible in an ink count, which is why it is a subset
     * test. */
    for (let i = 0; i < off.length; i++)
        assert(!off[i] || dflt[i], 'the fill punched a hole in the stroke');
});

step('the EQ curve draws nothing at all unless a bank declares one', () => {
    const bare = shot(() => draw(PAGE));
    const withEq = shot(() => draw(PAGE, { eq: { start: 0, count: 2, low: 0.5, mid: -0.5, high: 0.2 } }));
    assert(!same(bare, withEq), 'a declared eq drew nothing');
    /* No detection anywhere: the page has arc cells named nothing like an EQ
     * and must not sprout one. */
    assert(same(bare, shot(() => draw(PAGE, { eq: null }))), 'eq:null drew something');
});

step('a flat EQ is the zero line, and a boost and a cut differ', () => {
    const flat = shot(() => kit.drawKitEqCurve(kit.MV_ROW0_Y, { start: 0, count: 2, low: 0, mid: 0, high: 0 }));
    const boost = shot(() => kit.drawKitEqCurve(kit.MV_ROW0_Y, { start: 0, count: 2, low: 0, mid: 0.9, high: 0 }));
    const cut = shot(() => kit.drawKitEqCurve(kit.MV_ROW0_Y, { start: 0, count: 2, low: 0, mid: -0.9, high: 0 }));
    assert(ink(flat) > 0, 'a flat EQ drew nothing at all');
    assert(!same(boost, cut), 'a +9 boost and a -9 cut render the same');
    /* ⚠ BIPOLAR: the mass hangs from the CENTRE, so a cut fills DOWNWARD.
     * Filling to the floor instead would detach the shape from its own ink on
     * every cut, which is the honest reading inverted. */
    const fillCut = shot(() => kit.drawKitEqCurve(kit.MV_ROW0_Y, { start: 0, count: 2, low: 0, mid: -0.9, high: 0, fill: true }));
    let above = 0, below = 0;
    const midY = Math.round((kit.MV_ROW0_Y + 1 + kit.MV_ROW0_Y + kit.MV_KH - 2) / 2);
    for (let y = 0; y < H; y++) for (let x = 0; x < W; x++)
        if (fillCut[y * W + x] && !cut[y * W + x]) { if (y < midY) above++; else below++; }
    assert(below > above, 'a CUT filled upward (' + above + ' above vs ' + below + ' below)');
});

/* ------------------------------------------------------- 3. sample track */

step('an empty sample track with no markers draws NOTHING', () => {
    /* ⚠⚠ No frame, no baseline, no synthetic waveform. Upstream shipped a
     * representative shape here and deleted it after a device report: "no
     * sample was loaded, not sure why it was showing a waveform". */
    const nothing = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, { start: 0, count: 2 }));
    assert(ink(nothing) === 0, 'an empty sample cell drew ' + ink(nothing) + ' pixels');
    const emptyPeaks = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, { start: 0, count: 2, peaks: [] }));
    assert(ink(emptyPeaks) === 0, 'peaks:[] drew art');
});

step('markers alone still draw — an empty track is two real controls', () => {
    const cursor = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, { start: 0, count: 2, pos: 0.5 }));
    assert(ink(cursor) > 0, 'a cursor with no file drew nothing');
});

step('the playhead moves, the loop brackets point INWARD, spray adds a fence', () => {
    const peaks = Array.from({ length: 60 }, (_, i) => 0.5 + 0.4 * Math.sin(i / 3));
    const base = { start: 0, count: 2, peaks };
    const p1 = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, Object.assign({ pos: 0.2 }, base)));
    const p2 = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, Object.assign({ pos: 0.7 }, base)));
    assert(!same(p1, p2), 'the playhead did not move');
    const sprayed = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, Object.assign({ pos: 0.5, spray: 0.2 }, base)));
    const unsprayed = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, Object.assign({ pos: 0.5 }, base)));
    assert(!same(sprayed, unsprayed), 'spray drew no fence');
    /* ⚠ The tip COLUMNS are the assertion, not "are there brackets": reversing
     * the tips still draws two brackets and still satisfies any count, while
     * reading as a loop that excludes the part it actually plays. */
    const x0 = 1, w = 2 * kit.MV_CELL_W - 2, topY = kit.MV_ROW0_Y + 1;
    const open = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, { start: 0, count: 2, loopStart: 0.25 }));
    const stem = x0 + Math.min(w - 1, Math.floor(0.25 * w));
    assert(open[topY * W + stem + 1] === 1, 'the loop START tip does not point right (inward)');
    assert(!open[topY * W + stem - 1], 'the loop START tip points left (outward)');
    const close = shot(() => kit.drawKitSampleSpan(kit.MV_ROW0_Y, { start: 0, count: 2, loopEnd: 0.75 }));
    const stem2 = x0 + Math.min(w - 1, Math.floor(0.75 * w));
    assert(close[topY * W + stem2 - 1] === 1, 'the loop END tip does not point left (inward)');
});

/* ------------------------------------------------------- 4. label tilde */

step('the `~` appears only when modulated, and never over the touched VALUE', () => {
    const plain = shot(() => draw(PAGE));
    const tilde = shot(() => draw(PAGE.map((c, i) => (i === 0 ? Object.assign({}, c, { modulated: true }) : c))));
    assert(!same(plain, tilde), 'modulated:true changed no label');
    assert(same(plain, shot(() => draw(PAGE.map((c) => Object.assign({}, c, { modulated: false }))))),
           'modulated:false is not the default');
    /* While your finger is on the knob the strip is answering "what number is
     * this"; a modulation mark there competes with the answer. */
    const touchedPlain = shot(() => draw(PAGE, { touchedIdx: 0 }));
    const touchedMod = shot(() => draw(PAGE.map((c, i) => (i === 0 ? Object.assign({}, c, { modulated: true }) : c)),
                                       { touchedIdx: 0 }));
    assert(same(touchedPlain, touchedMod), 'the touched cell grew a tilde over its value');
});

step('ui_cells turns a live value into BOTH marks, and no value into neither', () => {
    const desc = { key: 'cutoff', kind: 'uni', label: 'Cutoff', short: 'Cutf', min: 0, max: 100, type: 'float' };
    const off = cells.toRenderCell(desc, 40, null, null);
    assert(off.modNorm === null && off.modulated === false, 'no source still marked modulated');
    const on = cells.toRenderCell(desc, 40, null, 70);
    assert(on.modulated === true && Math.abs(on.modNorm - 0.7) < 1e-9, 'modNorm mis-normalised: ' + on.modNorm);
    /* ⚠ null IS NOT zero. Number('') is 0, which is finite — an unmodulated
     * cell would pin its dot at the bottom of the range on every page. */
    assert(cells.toRenderCell(desc, 40, null, '').modulated === false, 'empty string read as a value');
    /* Coincidence is not absence: a source sitting on the base is modulated. */
    assert(cells.toRenderCell(desc, 40, null, 40).modulated === true, 'a coincident source read as unmodulated');
});

/* --------------------------------------------------------- 5. enum peek */

step('the peek timer is pure, and a knob never turned has not expired', () => {
    assert(kit.MV_ENUM_PEEK_MS === 700, 'the peek window drifted from upstream ENUM_PEEK_MS');
    assert(kit.enumPeekExpired(1000, 1000 + 699) === false, 'expired inside the window');
    assert(kit.enumPeekExpired(1000, 1000 + 701) === true, 'never expired');
    /* ⚠ Number(null) is 0, which against any real clock is expired — so a
     * caller that had not yet recorded a turn would suppress the list for ever. */
    assert(kit.enumPeekExpired(null, Date.now()) === false, 'a never-turned knob read as expired');
    assert(kit.enumPeekExpired(undefined, Date.now()) === false, 'undefined read as expired');
});

step('peekExpired takes the option list down, and is OFF by default', () => {
    const ENUM = [{ kind: 'enumsq', label: 'S', name: 'Shape', text: 'SAW',
                    options: ['SINE', 'TRI', 'SAW', 'SQR'], sel: 2 },
                  PAGE[1], PAGE[2], PAGE[3], PAGE[4], PAGE[5], PAGE[6], PAGE[7]];
    const up = shot(() => draw(ENUM, { touchedIdx: 0, overlayIdx: 0 }));
    const down = shot(() => draw(ENUM, { touchedIdx: 0, overlayIdx: 0, peekExpired: true }));
    assert(!same(up, down), 'peekExpired did not take the list down');
    assert(ink(down) < ink(up), 'the "expired" page has MORE ink than the list');
    /* Omitting the flag must keep today's hold-to-show behaviour exactly. */
    assert(same(up, shot(() => draw(ENUM, { touchedIdx: 0, overlayIdx: 0, peekExpired: false }))),
           'peekExpired defaults to on');
});

/* ------------------------------------------------- 6. mockups stay unwired */

step('MOCKUP kinds are reachable but nothing maps to them', () => {
    const pill = shot(() => kit.drawSwitchPill(6, kit.MV_ROW0_Y, true));
    const pillOff = shot(() => kit.drawSwitchPill(6, kit.MV_ROW0_Y, false));
    assert(ink(pill) > 0 && ink(pillOff) > 0, 'a pill state drew nothing');
    /* THE TRACK CARRIES THE STATE: ON fills the track and knocks the slug out,
     * so the two states differ by most of the widget's AREA — which is the
     * whole reason this beat a slug-only pill, and the reason it survives being
     * shrunk to 16x9. Measured as the SYMMETRIC DIFFERENCE over the pill's own
     * rect, not as an ink ratio: a widget that merely slid a 5px block would
     * score 50 differing pixels out of 144, where this scores most of them. */
    let differ = 0;
    for (let i = 0; i < pill.length; i++) if (pill[i] !== pillOff[i]) differ++;
    /* Measured: 56 of the pill's 144 pixels, and OFF's ink is a strict SUBSET
     * of ON's (the OFF slug sits inside ON's filled track, ON's knocked-out
     * slug sits inside OFF's empty one) — so the symmetric difference is
     * exactly the ink difference. A slug-only pill would score about 50 in the
     * difference and 1.0 in the ratio; this scores 56 and 1.9. Both are
     * asserted because either alone is satisfiable by the wrong widget. */
    assert(differ >= 50, 'ON and OFF differ in only ' + differ + ' of 144 pixels');
    assert(ink(pill) > ink(pillOff) * 1.7,
           'ON carries only ' + (ink(pill) / ink(pillOff)).toFixed(2) + 'x the ink of OFF — the slug is carrying the state');
    assert(ink(shot(() => kit.drawFaderColumn(6, kit.MV_ROW0_Y, 0.5))) > 0, 'the fader drew nothing');
    /* `faderail` stayed a renderer-only alias when the fader was adopted: a
     * `fader` descriptor still says `vbar`, and the DISPATCH decides what that
     * looks like. If ui_cells ever starts emitting the alias, the look has two
     * homes and the next restyle will only reach one of them. */
    const KINDS = ['uni', 'bip', 'tog', 'enumc', 'len', 'dir', 'count', 'oct', 'file', 'fader'];
    for (const k of KINDS) {
        const rc = cells.toRenderCell({ key: 'k', kind: k, label: 'L', min: 0, max: 10, type: 'int',
                                        options: (k === 'enumc' ? ['A', 'B', 'C'] : null) }, 5, 'x');
        assert(!rc || rc.kind !== 'faderail',
               'kind ' + k + ' now emits the renderer-only alias');
    }
    /* A `fader` cell must still say `vbar` — the adoption is in the dispatch. */
    const fader = cells.toRenderCell({ key: 'f', kind: 'fader', label: 'L', min: 0, max: 1, type: 'float' }, 0.5);
    assert(fader.kind === 'vbar', 'a fader descriptor no longer says vbar (' + fader.kind + ')');
    /* ...and `vbar` must DRAW as the fader column, not the plain bar. */
    const cellFader = shot(() => draw([fader, null, null, null, null, null, null, null]));
    const plainBar = shot(() => kit.drawVBar(6, kit.MV_ROW0_Y, 0.5));
    let overlap = 0;
    for (let i = 0; i < plainBar.length; i++) if (plainBar[i] && cellFader[i]) overlap++;
    assert(overlap < ink(plainBar) * 0.9, 'a vbar cell still draws the plain bar');
});

/* ------------------------------------- the PILL / BAR / BOX split (adopted) */

step('a two-state cell picks its widget from its OWN OPTIONS, by one rule', () => {
    const tog = (options) => cells.toRenderCell(
        { key: 'k', kind: 'tog', type: 'enum', label: 'L', min: 0, max: 1, step: 1, options }, 1);
    /* Both halves in the boolean vocabulary -> PILL. Case-insensitive, because
     * Track View spells its states 'ON' and 'off'. Digits count: a module that
     * spells its toggle ["0","1"] means a boolean. */
    for (const pair of [['Off', 'On'], ['ON', 'off'], ['No', 'Yes'], ['0', '1'],
                        ['false', 'true'], ['Disabled', 'Enabled']]) {
        assert(tog(pair).kind === 'pill', pair.join('/') + ' did not take the pill');
    }
    /* A pair of WORDS -> the enum BOX, which prints the word. Not the bar it
     * used to take: that showed a fill level and nothing else, so Step/Audio
     * read as "full" or "empty". */
    for (const pair of [['Step', 'Audio'], ['Mono', 'Poly'], ['LP', 'HP'], ['Sine', 'Saw']]) {
        assert(tog(pair).kind === 'enumsq', pair.join('/') + ' did not take the box');
    }
    /* ⚠ HALF A PAIR IS NOT A BOOLEAN. 'Off'/'Lock' is a toggle whose ON state
     * is NAMED, and naming it was a choice the widget must not throw away. */
    assert(tog(['Off', 'Lock']).kind === 'enumsq', 'half a boolean pair took the pill');
    assert(tog(['Bypass', 'On']).kind === 'enumsq', 'half a boolean pair took the pill');
    /* A box carries its options so the turn-to-reveal picker still works; a
     * pill does not need them but must not have lost them either. */
    assert(tog(['Step', 'Audio']).options.length === 2, 'the box lost its option list');
    assert(tog(['Off', 'On']).sel === 1, 'the pill lost its selection');
});

step('the pill and the box actually LOOK different, and the box shows the word', () => {
    const mk = (options, v) => cells.toRenderCell(
        { key: 'k', kind: 'tog', type: 'enum', label: 'L', min: 0, max: 1, step: 1, options }, v);
    const boolOn = shot(() => draw([mk(['Off', 'On'], 1), null, null, null, null, null, null, null]));
    const boolOff = shot(() => draw([mk(['Off', 'On'], 0), null, null, null, null, null, null, null]));
    assert(!same(boolOn, boolOff), 'the pill draws its two states identically');
    /* The BOX must differ between its two states too — which the bar it
     * replaced also did, but only as a fill level. Here the difference is the
     * WORD, so the two frames differ inside the frame rather than by area. */
    const wordA = shot(() => draw([mk(['Step', 'Audio'], 0), null, null, null, null, null, null, null]));
    const wordB = shot(() => draw([mk(['Step', 'Audio'], 1), null, null, null, null, null, null, null]));
    assert(!same(wordA, wordB), 'the box draws Step and Audio identically');
    /* ⚠ And the box must not be the pill: if the split ever collapses, both
     * branches still draw SOMETHING and only a comparison catches it. */
    assert(!same(boolOn, wordB), 'the pill and the box render the same pixels');
});

step('the fader lattice re-phases where the bar cannot move', () => {
    /* The whole argument for the fader over the vbar: a 128-step param gets ~10
     * detents per row of travel, so nine in ten move nothing.
     *
     * ⚠⚠ THE PAIR IS DERIVED, NOT WRITTEN DOWN. It was hardcoded (0.500/0.520)
     * and went stale the moment the widget box changed 16 -> 15 to buy the
     * footer: at the new band height both values land in the same DIAG_HEAVY
     * phase, so the test failed while the feature was fine. A hardcoded pair
     * here is a pin on the geometry pretending to be a pin on the fill.
     *
     * So: search for two values that share a boundary row and differ in phase,
     * and FAIL IF NONE EXISTS — because that is the real regression (a band so
     * short the sub-row phase cannot express anything), and a search that
     * quietly finds nothing would report it as a pass. */
    const h = kit.MV_KH - 3;                 /* drawFaderColumn: bot - top */
    const phaseOf = (v) => Math.floor((v * h - Math.floor(v * h)) * 4) % 4;
    let lo = -1, hi = -1;
    for (let i = 1; i < 1000 && lo < 0; i++) {
        const x = i / 1000;
        for (let j = i + 1; j < 1000; j++) {
            const y = j / 1000;
            if (Math.round(x * h) !== Math.round(y * h)) continue;   /* same boundary */
            if (Math.round(x * 12) !== Math.round(y * 12)) continue; /* vbar agrees too */
            if (phaseOf(x) === phaseOf(y)) continue;                 /* but the phase moves */
            /* ⚠ AND THE BAR MUST HAVE AN INTERIOR TO DITHER. Below ~3 rows the
             * fader degrades to a solid 7x2 stub with no lattice at all
             * (`bh >= 3` in drawFaderColumn), so the first pair the search
             * found — 0.001 vs 0.021 — differed in phase and drew IDENTICAL
             * pixels, which is the widget behaving correctly and the test
             * asking the wrong question. */
            if (Math.round(x * h) < 3) continue;
            lo = x; hi = y; break;
        }
    }
    assert(lo >= 0, 'no sub-row pair exists at MV_KH=' + kit.MV_KH +
                    ' — the band is too short for the lattice to say anything');
    const a = shot(() => kit.drawFaderColumn(6, kit.MV_ROW0_Y, lo));
    const b = shot(() => kit.drawFaderColumn(6, kit.MV_ROW0_Y, hi));
    assert(!same(a, b), 'a sub-row detent changed no pixel — the phase is not wired');
    const va = shot(() => kit.drawVBar(6, kit.MV_ROW0_Y, lo));
    const vb = shot(() => kit.drawVBar(6, kit.MV_ROW0_Y, hi));
    assert(same(va, vb), 'the vbar comparison is not actually sub-row (' + lo + '/' + hi + ')');
});

/* ------------------------------------------------------ 7. knob ring LEDs */

step('a BOUND knob is never dark, and an UNBOUND one is always colour 0', () => {
    for (let k = 0; k < 8; k++) {
        for (const v of [0, 0.001, 0.5, 1]) {
            assert(rings.knobRingColor(k, v) !== 0,
                   'knob ' + k + ' at ' + v + ' is unlit — the floor must not be zero');
        }
        /* ⚠ Colour 0 is RESERVED for "nothing is bound here". An unread key is
         * not a value of zero, and lighting it at the bottom of the ramp would
         * be a confident lie about where the parameter sits. */
        for (const v of [null, undefined, NaN, Infinity]) {
            assert(rings.knobRingColor(k, v) === 0, 'knob ' + k + ' lit for ' + String(v));
        }
    }
});

step('both ramps rise monotonically — a dip is the "curve is weird" bug', () => {
    /* ⚠⚠ Upstream picked its amber constants by NAME and got
     * dim -> bright -> DARK -> bright, reported from the device as "the LEDs
     * work but the curve is off". Ordering is asserted, not assumed. */
    const WHITE_ORDER = rings.KNOB_WHITE_LEVELS;
    const AMBER_ORDER = rings.KNOB_AMBER_LEVELS;
    assert(WHITE_ORDER.length >= 2 && AMBER_ORDER.length >= 2, 'a ramp has fewer than two steps');
    assert(new Set(WHITE_ORDER).size === WHITE_ORDER.length, 'the white ramp repeats a colour');
    assert(new Set(AMBER_ORDER).size === AMBER_ORDER.length, 'the amber ramp repeats a colour');
    /* The ramp index must never go DOWN as the value goes up — for every knob,
     * over a fine sweep, which is what catches an out-of-order constant. */
    for (let k = 0; k < 8; k++) {
        const ramp = k < 4 ? WHITE_ORDER : AMBER_ORDER;
        let last = -1;
        for (let i = 0; i <= 100; i++) {
            const idx = ramp.indexOf(rings.knobRingColor(k, i / 100));
            assert(idx >= 0, 'knob ' + k + ' returned a colour outside its own ramp');
            assert(idx >= last, 'knob ' + k + ' ramp dips at ' + i + '%');
            last = idx;
        }
        assert(last === ramp.length - 1, 'knob ' + k + ' never reaches the top of its ramp');
    }
    /* ⚠ The thresholds are DERIVED from the ramp, not written beside it: every
     * entry must be reachable, which is what a hard-coded 0.33/0.67 breaks the
     * moment a ramp gains a step. */
    for (let k = 0; k < 8; k++) {
        const ramp = k < 4 ? WHITE_ORDER : AMBER_ORDER;
        const seen = new Set();
        for (let i = 0; i <= 1000; i++) seen.add(rings.knobRingColor(k, i / 1000));
        assert(seen.size === ramp.length, 'knob ' + k + ': ' + seen.size + ' of ' + ramp.length + ' ramp steps reachable');
    }
    /* Rows must differ by HUE at EVERY level — a white knob at minimum must
     * not be mistakable for an amber one at minimum. */
    for (let i = 0; i <= 10; i++) {
        assert(rings.knobRingColor(0, i / 10) !== rings.knobRingColor(4, i / 10),
               'white and amber collide at ' + (i * 10) + '%');
    }
});

step('an unbound or degenerate bank knob normalises to null, not to zero', () => {
    const knob = { abbrev: 'Cut', min: 0, max: 100, def: 0, scope: 'clip' };
    assert(rings.knobRingNorm(knob, 50) === 0.5, 'a plain knob mis-normalised');
    assert(rings.knobRingNorm(knob, 0) === 0, 'a knob at its minimum is not 0');
    assert(rings.knobRingNorm(null, 5) === null, 'an empty slot normalised');
    assert(rings.knobRingNorm({ abbrev: 'S', scope: 'stub', min: 0, max: 1 }, 1) === null, 'a stub normalised');
    assert(rings.knobRingNorm({ abbrev: 'X', min: 3, max: 3 }, 3) === null, 'a degenerate range normalised');
    assert(rings.knobRingNorm(knob, undefined) === null, 'an unread value normalised to a number');
    /* The two halves compose to the reserved dark: unbound -> null -> 0. */
    assert(rings.knobRingColor(0, rings.knobRingNorm(null, 0)) === 0, 'an empty slot lit its ring');
});

/* -------------------------------------------------------- 8. scrollbar */

step('the dotted rail is the DEFAULT, and the thumb stays solid on top of it', () => {
    const ROWS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
    const dflt = shot(() => kit.drawKitList(ROWS, 3, {}));
    const dotted = shot(() => kit.drawKitList(ROWS, 3, { dottedRail: true }));
    const solid = shot(() => kit.drawKitList(ROWS, 3, { dottedRail: false }));
    assert(same(dflt, dotted), 'the default is not the dotted rail');
    assert(!same(solid, dotted), 'dottedRail:false changed nothing');
    /* ⚠ The RAIL thins, the THUMB does not — otherwise the thumb is just a
     * thicker piece of the same object and the eye has to measure widths to
     * read a position. Count both columns of the thumb, which is drawn over
     * the rail after it. */
    let railGaps = 0, thumbSolid = 0;
    for (let y = 0; y < H; y++) {
        if (solid[y * W + 126] && !dotted[y * W + 126]) railGaps++;
        if (dotted[y * W + 125] && dotted[y * W + 126]) thumbSolid++;
    }
    assert(railGaps > 5, 'the rail did not become dotted (' + railGaps + ' cleared rows)');
    assert(thumbSolid >= 3, 'the thumb is not a solid 2px block (' + thumbSolid + ' rows)');
});

/* A short list has no overflow, so neither rail nor thumb exists and the flag
 * must be inert rather than drawing a rail with nothing to say. */
step('a list that fits draws no rail at all, dotted or otherwise', () => {
    const SHORT = ['A', 'B'];
    assert(same(shot(() => kit.drawKitList(SHORT, 0, {})),
                shot(() => kit.drawKitList(SHORT, 0, { dottedRail: true }))),
           'a non-overflowing list drew a scrollbar');
});

/* ================= the 2026-08-29 second batch ========================== */

const fonts = await import('../../ui/ui_fonts_pp.mjs');
const animMod = await import('../../ui/ui_anim.mjs');

step('the ported faces measure what upstream measures, and AUDIO no longer wraps', () => {
    /* ⚠⚠ THE WHOLE POINT OF PORTING A TABLE IS THAT IT IS THE SAME TABLE. A
     * transcription that renders "close enough" is a second face, and the two
     * would drift the first time either was touched. Widths are the cheapest
     * total check: a single wrong glyph row changes one, and every string in
     * the product is laid out from them. */
    assert(fonts.fontWidth4x5('AUDIO') === 21, 'the 4x5 face re-measured AUDIO');
    assert(fonts.BIGNUM_H === 11, 'the big face is not 11 rows');
    assert(fonts.TAMZEN_H === 7, 'the tamzen face is not 7 rows');
    /* THE BUG THIS RETIRES: the old blind 4/4 slice rendered AUDIO as AUDI/O.
     * 21px against a 24px interior fits whole. */
    const fits = (t) => fonts.fontWidth4x5(t) <= 24;
    assert(JSON.stringify(fonts.enumSquareLines('AUDIO', fits)) === '["AUDIO",""]',
           'AUDIO still wraps');
    /* ⚠ "Does it need to break AT ALL" is asked FIRST. POLY and I+II both fit
     * whole and neither reads as itself once split. */
    assert(fonts.enumSquareLines('POLY', fits)[1] === '', 'POLY was split');
    assert(fonts.enumSquareLines('I+II', fits)[1] === '', 'I+II was split');
    /* ⚠ A `+` INSIDE a word is a break opportunity and must stay VISIBLE — a
     * blind slice turns I+II into "I+I"/"I", which is a DIFFERENT VALUE and
     * indistinguishable from mode "I". Forced to break by a tiny budget. */
    const tiny = () => false;
    const pl = fonts.enumSquareLines('I+II', tiny);
    assert(pl[0].indexOf('+') >= 0, 'the + was dropped from the break');
    /* ⚠ `-` between word characters separates; a leading one does not, or
     * "+-1" loses its minus entirely. */
    assert(fonts.enumSquareLines('+-1', fits)[1] === '', '+-1 was split');
    /* ⚠ 12 GLYPHS ONLY, and the caller must ask. Anything with a letter has to
     * fall back or "C1 36" silently becomes "1 36". */
    assert(fonts.bigNumCanDraw('-12') === true, 'the big face refused a number');
    assert(fonts.bigNumCanDraw('E 3') === false, 'the big face claimed a note name');
    assert(fonts.bigNumCanDraw('') === false, 'the big face claimed the empty string');
});

step('the enum square sizes to its VALUE, and the line count ignores the frame', () => {
    const sq = (t) => shot(() => kit.drawEnumSquare(2, kit.MV_ROW0_Y, t));
    assert(kit.enumSquareWidth('ON') < kit.enumSquareWidth('BANDPASS'),
           'a short value takes the same width as a long one');
    assert(kit.enumSquareWidth('BANDPASS') <= kit.MV_ENUM_W, 'the cap does not bind');
    assert(kit.enumSquareWidth('I') >= kit.MV_ENUM_MIN_W, 'the floor does not bind');
    assert(!same(sq('ON'), sq('BANDPASS')), 'two values drew the same box');
});

step('only the FRAME animates, and a value ARRIVING does not animate at all', () => {
    /* ⚠⚠ THE FAILURE THIS PINS. The read cursor serves one key per tick, so a
     * page spends its first ticks with values absent — rendered as "--", which
     * has a perfectly ordinary width. Recorded as a first sighting, the real
     * value then arrives as a TRANSITION and the whole page animates itself in
     * from values nobody set. observeLanded is what refuses that, and it can
     * only do it from the RAW value. */
    const st = animMod.createAnimState();
    const at = (t, txt, raw, store) =>
        shot(() => kit.drawEnumSquare(2, kit.MV_ROW0_Y, txt, null, store, t, 'k', raw));

    /* An unread key (raw undefined) records NOTHING and draws at natural width. */
    const absent = at(0, '--', undefined, st);
    const absentStatic = shot(() => kit.drawEnumSquare(2, kit.MV_ROW0_Y, '--'));
    assert(same(absent, absentStatic), 'an unread value animated');

    /* The real value ARRIVES: first sighting, stamped already-past. */
    const arrive = at(0, 'BANDPASS', 'BANDPASS', st);
    const arriveStatic = shot(() => kit.drawEnumSquare(2, kit.MV_ROW0_Y, 'BANDPASS'));
    assert(same(arrive, arriveStatic), 'a value ARRIVING animated — that is not a change');

    /* Now a genuine change, caught mid-flight. */
    const mid = at(60, 'ON', 'ON', st);
    const settled = shot(() => kit.drawEnumSquare(2, kit.MV_ROW0_Y, 'ON'));
    assert(!same(mid, settled), 'a real change did not animate');
    const done = at(60 + kit.MV_ENUM_ANIM_MS + 1, 'ON', 'ON', st);
    assert(same(done, settled), 'the animation never settled');

    /* ⚠ NO STORE => NOTHING MOVES, which is what keeps every existing caller
     * byte-identical. */
    assert(same(shot(() => kit.drawEnumSquare(2, kit.MV_ROW0_Y, 'ON', null, null, 999, 'k', 'ON')),
                settled), 'a missing store still animated');
});

step('the button has three states, and two presses in flight do not merge', () => {
    const now = 1000;
    const idle = shot(() => kit.drawTriggerButton(6, kit.MV_ROW0_Y, kit.buttonPhase(0, now, false)));
    const held = shot(() => kit.drawTriggerButton(6, kit.MV_ROW0_Y, kit.buttonPhase(0, now, true)));
    const fired = shot(() => kit.drawTriggerButton(6, kit.MV_ROW0_Y, kit.buttonPhase(now - 40, now, false)));
    assert(ink(held) > ink(idle), 'the held cap is not filled');
    assert(!same(idle, fired), 'a fired button looks idle');
    /* ⚠ ONE BURST PER PRESS STILL IN FLIGHT. Overwriting a single timestamp
     * made a rapid second press swallow the first ring and restart from the
     * centre — an animation glitch rather than two events. */
    const one = kit.buttonPhase([now - 40], now, false);
    const two = kit.buttonPhase([now - 40, now - 240], now, false);
    assert(two.bursts.length === 2 && one.bursts.length === 1, 'the second press was swallowed');
    /* An expired press contributes nothing, and a FUTURE stamp is ignored
     * rather than producing a negative-progress ring. */
    assert(kit.buttonPhase([now - kit.BTN_FLASH_MS - 1], now, false).bursts.length === 0,
           'an expired press still burst');
    assert(kit.buttonPhase([now + 50], now, false).bursts.length === 0,
           'a future timestamp burst');
    /* No `now` at all => idle. The draw path must never need a clock. */
    assert(kit.buttonPhase([now], undefined, false).bursts.length === 0, 'a clockless phase fired');
});

step('the opaque box spells the tri-state, and the brackets are separate from the chevron', () => {
    const box = (t) => shot(() => kit.drawOpaqueBox(0, kit.MV_ROW0_Y, t));
    const val = box('KICK_01.WAV'), none = box('NONE'), unread = box('--');
    assert(!same(val, none) && !same(none, unread) && !same(val, unread),
           'two of the three states render identically');
    /* ⚠ A PLACEHOLDER IS CENTRED, A VALUE IS SET LEFT — reported from the
     * device as "not centered by the way". Compare the leftmost lit column of
     * the TEXT area against the value's. */
    const firstTextCol = (f) => {
        for (let x = 4; x < kit.MV_CELL_W - 6; x++)
            for (let y = kit.MV_ROW0_Y + 3; y < kit.MV_ROW0_Y + 12; y++)
                if (f[y * W + x]) return x;
        return -1;
    };
    assert(firstTextCol(none) > firstTextCol(val), 'NONE is not centred');
    /* The door mark is drawn around the CELL, after the widget, so it is
     * independent of what the widget is — a bracket over an ARC must work. */
    const plainArc = shot(() => draw(PAGE));
    const opensArc = shot(() => draw(PAGE.map((c, i) => (i === 0 ? Object.assign({}, c, { opens: true }) : c))));
    assert(!same(plainArc, opensArc), 'the brackets did not draw over an arc cell');
    /* ⚠ MUST STAY INSIDE THE WIDGET BAND — one row of overflow lands on the
     * label strip and the brackets merge into it. */
    for (let x = 0; x < W; x++)
        assert(!opensArc[(kit.MV_LBL0_Y) * W + x] || plainArc[(kit.MV_LBL0_Y) * W + x],
               'a bracket leaked onto the label strip');
});

step('ui_cells spells the file tri-state, and does not collapse empty into unread', () => {
    const d = { key: 'sample_path', kind: 'file', type: 'file', label: 'Sample', min: 0, max: 0 };
    assert(cells.toRenderCell(d, null, '/a/b/kick.wav').text === 'KICK.WAV', 'the basename was lost');
    /* ⚠ THE BUG: `rawValue ? ... : "--"` collapsed '' into the unread case,
     * because '' is falsy — so a slot with no file looked exactly like a slot
     * whose name had not arrived. */
    assert(cells.toRenderCell(d, null, '').text === 'NONE', 'an empty path read as unread');
    assert(cells.toRenderCell(d, null, null).text === '--', 'an unread path read as empty');
    assert(cells.toRenderCell(d, null, undefined).text === '--', 'undefined read as empty');
    assert(cells.toRenderCell(d, null, '').kind === 'opaque', 'a file is not an opaque cell');
    assert(cells.toRenderCell(d, null, '').opens === true, 'a file cell is not a door');
});

step('the waveform morphs between shapes, and never out of an unread one', () => {
    const st = animMod.createAnimState();
    const w = (shape, t, raw, store) =>
        shot(() => kit.drawWaveBox(6, kit.MV_ROW0_Y, shape, store, t, 'w', raw));
    const sineStatic = shot(() => kit.drawWaveBox(6, kit.MV_ROW0_Y, 'sine'));
    const sawStatic = shot(() => kit.drawWaveBox(6, kit.MV_ROW0_Y, 'saw'));
    /* An unread key records nothing and draws the plain shape. */
    assert(same(w('sine', 0, undefined, st), sineStatic), 'an unread shape animated');
    assert(same(w('sine', 0, 'sine', st), sineStatic), 'a shape ARRIVING animated');
    /* ⚠ THE TRANSITION STARTS ON THE FRAME THE VALUE CHANGES, and at that
     * instant t === 0, so the first `saw` frame draws the SINE. Sampling there
     * would "prove" the morph works while actually showing it not having begun
     * — which is the same frame a broken morph would produce. Start it, then
     * sample HALFWAY. */
    w('saw', 0, 'saw', st);
    const mid = w('saw', 50, 'saw', st);
    assert(!same(mid, sawStatic) && !same(mid, sineStatic), 'the morph produced no in-between');
    assert(same(w('saw', kit.MV_WAVE_MORPH_MS + 1, 'saw', st), sawStatic),
           'the morph never settled');
    assert(same(w('saw', 0, 'saw', null), sawStatic), 'a missing store still morphed');
});

step('the footer reserves BACK before laying anything else out', () => {
    /* ⚠⚠ THE FIT RULE, and the reason this is a primitive and not a loop. A
     * naive left-to-right layout drops whatever does not fit — which on a
     * narrow row is the LAST hint, and the last hint is BACK. A footer that
     * silently drops the one hint telling you how to leave is worse than a
     * footer with three hints on it. */
    const many = [['JOG', 'PAGE'], ['CLK', 'MENU'], ['SHFT', 'ALT'], ['MUTE', 'BYPASS'],
                  ['KNB', 'EDIT'], ['BACK', 'EXIT']];
    const total = many.reduce((a, h) => a + kit.hintPairWidth(h[0], h[1]), 0);
    assert(total > 128, 'the over-ask test does not actually over-ask (' + total + 'px)');
    const drawn = shot(() => { const d = kit.drawKitHintRow(20, many); assert(d < many.length,
        'nothing was dropped — the row was not over-asked'); });
    /* BACK's pill must be present, hard against the right edge. */
    const backW = kit.hintPairWidth('BACK', 'EXIT');
    let lit = 0;
    for (let y = 19; y < 19 + kit.MV_FOOTER_H; y++)
        for (let x = 128 - backW; x < 128; x++) if (drawn[y * W + x]) lit++;
    assert(lit > 10, 'BACK was dropped or is not at the right edge (' + lit + ' px)');
    assert(kit.isBackHint(['Back', 'out']) && !kit.isBackHint(['CLK', 'MENU']),
           'the back hint is not recognised case-insensitively');
    assert(kit.drawKitHintRow(20, []) === 0 && kit.drawKitHintRow(20, null) === 0,
           'an empty footer drew something');
});

step('the big-number cell uses the ported face, and FALLS BACK on a letter', () => {
    /* Two different faces must produce two different pictures for the same
     * cell; if the fallback silently stopped firing, a note name would lose its
     * letters and still look like a number. */
    const num = shot(() => kit.drawBigNum(0, kit.MV_ROW0_Y, '127'));
    assert(ink(num) > 0, 'a plain number drew nothing');
    const note = shot(() => kit.drawBigNum(0, kit.MV_ROW0_Y, 'E 3'));
    assert(ink(note) > 0, 'a note name drew NOTHING — the fallback is gone');
    /* The letter must actually be there: drawing only the digit would also be
     * "> 0 ink". Compare against the digit alone. */
    const digit = shot(() => kit.drawBigNum(0, kit.MV_ROW0_Y, '3'));
    assert(ink(note) > ink(digit), 'the note name rendered as its digit alone');
});

step('the picker overlay carries the same dotted rail as the list beneath it', () => {
    const OPTS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'];
    const ov = shot(() => kit.drawKitListOverlay(OPTS, 4));
    /* Find the rail column: the overlay auto-sizes, so locate it from the box. */
    let gaps = 0, run = 0;
    for (let x = 0; x < W; x++) {
        let colGaps = 0, colLit = 0, prev = 0;
        for (let y = kit.MV_ZOOM_Y; y < kit.MV_ZOOM_Y + kit.MV_ZOOM_H; y++) {
            const v = ov[y * W + x];
            if (v) colLit++; else if (prev) colGaps++;
            prev = v;
        }
        if (colLit > 8 && colGaps > 5) { gaps = colGaps; run = colLit; }
    }
    assert(gaps > 5 && run > 8, 'no dotted rail found in the overlay (gaps=' + gaps + ')');
});

console.log(failed ? '\nFAILED' : '\nAll widget-pixel checks passed.');
process.exit(failed);
}
main();
