#!/usr/bin/env python3
"""gen-splash-pool.py — regenerate davebox/ui/ui_splash.mjs from daves/.

THE ONE STEP for adding a Dave (Josh, 2026-08-31):
  0. from a photo? tools/dave-maker/ converts it (Josh's portable maker,
     also installed as the move-dave-maker skill):
       python3 tools/dave-maker/scripts/make_move_dave.py IN.jpg NAME.png
     Read tools/dave-maker/SKILL.md + references/tuning.md before tuning.
  1. drop the 128x64 1-bit PNG into daves/ — THE FILENAME IS THE DAVE'S NAME.
     A repeat of an existing Dave (a different image of the same name) is
     saved as "<NAME> 2.png", "<NAME> 3.png", ... — the first keeps the bare
     name, and the ordinal must be the next unused one (validated below).
  2. add a manifest.tsv row with the NEXT dave_num (numbers are PERMANENT —
     never renumber, never reuse; the script refuses duplicates) and a rarity
  3. run this script, then standalone/scripts/make-splashes.mjs
  4. commit all three; tests/host/test_splash_assets.sh pins the sync

Rarity -> pick weight (the Dave Box gacha): common 1.0, uncommon 0.5,
rare 0.3. With 30 commons + 1 rare that puts DAVIES at ~1 in 101 launches —
Josh's "~1 in 100" ruling. Weights live HERE so the manifest stays editorial
(a word, not a float).

Ordering in the emitted pool is dave_num ascending, so splash-<i>.hex indices
stay aligned with collection order. Frame INDEX is build-local; dave_num is
the permanent identity the seen-file records.
"""
import sys, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DAVES = os.path.join(REPO, 'daves')
OUT = os.path.join(REPO, 'davebox', 'ui', 'ui_splash.mjs')

WEIGHTS = {'common': 1.0, 'uncommon': 0.5, 'rare': 0.3}

rows = [l.rstrip('\n').split('\t') for l in open(os.path.join(DAVES, 'manifest.tsv'))]
hdr, data = rows[0], rows[1:]
col = {name: i for i, name in enumerate(hdr)}
for need in ('file', 'name', 'dave_num', 'rarity'):
    assert need in col, f'manifest.tsv missing column {need}'

daves = []
for r in data:
    n = int(r[col['dave_num']])
    rarity = r[col['rarity']]
    fn = r[col['file']]
    # A Dave's NAME IS HIS FILENAME (Josh, 2026-08-31) — the manifest name
    # column is display metadata that must agree, so drift is an error.
    name = os.path.splitext(fn)[0]
    assert r[col['name']] == name, f"manifest name {r[col['name']]!r} != filename {name!r}"
    assert rarity in WEIGHTS, f"unknown rarity {rarity!r} for {name}"
    daves.append((n, name, fn, WEIGHTS[rarity], rarity.upper()))
nums = [n for n, *_ in daves]
assert len(nums) == len(set(nums)), 'duplicate dave_num — numbers are permanent, use the next one'
names = [d[1] for d in daves]
assert len(names) == len(set(names)), 'duplicate display name — a repeat Dave is "<NAME> 2"'
daves.sort()
# Repeat-Dave ordinals must be sequential in dave_num order: "BOWIE 2" needs a
# bare BOWIE before it, "BOWIE 3" needs a "BOWIE 2", and "BOWIE 1" is refused
# (the first of a name is bare). A bare all-digit name like 2001 is untouched —
# only "<something> <digits>" parses as a repeat.
import re as _re
seen_bases = {}
for _, name, *_rest in daves:
    m = _re.fullmatch(r'(.+) (\d+)', name)
    if m:
        base, k = m.group(1), int(m.group(2))
        assert k >= 2, f'{name!r}: the first of a name is bare, repeats start at 2'
        assert seen_bases.get(base, 1) == k - 1, \
            f'{name!r}: expected ordinal {seen_bases.get(base, 1) + 1} next for {base!r}'
        seen_bases[base] = k
    else:
        assert name not in seen_bases or seen_bases[name] == 1, name
        seen_bases.setdefault(name, 1)

frames = []
for n, name, fn, w, rword in daves:
    im = Image.open(os.path.join(DAVES, fn)).convert('L')
    assert im.size == (128, 64), f'{fn} is {im.size}, need 128x64'
    by = bytearray(1024)
    for y in range(64):
        for x in range(128):
            if im.getpixel((x, y)) >= 128:
                by[y * 16 + (x >> 3)] |= 1 << (7 - (x & 7))
    frames.append((n, name, w, rword, bytes(by).hex()))

hex_body = '\n'.join(f"    /* Dave {n}: {name} */\n    '{h}'," for n, name, _, _, h in frames)
dave_body = '\n'.join(f"    {{ n: {n}, name: '{name}', w: {w}, r: '{rw}' }},"
                      for n, name, w, rw, _ in frames)

open(OUT, 'w').write(f"""/* ⚠ GENERATED by standalone/scripts/gen-splash-pool.py from daves/ — edit the
 * PNGs and manifest.tsv, not this file. See that script's docstring for the
 * add-a-Dave procedure. tests/host/test_splash_assets.sh pins the sync.
 *
 * NO LONGER RENDERED AS THE MODULE'S LOADING SCREEN (v3, 2026-08-07): the
 * artwork shows ONCE per launch (quiesce-stock.sh, or ensureCustomSplash in
 * shadow_ui.js on the pre-kill branch), picked WEIGHTED-random from this pool.
 * The frame shown is recorded by dave_num into the device-global collection
 * file (daves-seen.txt) — the Dave Box slideshow in the global settings menu
 * shows every Dave the user has ever been dealt. Frame INDEX here is
 * build-local; dave_num is the permanent identity.
 *
 * 1 bit per pixel, MSB-first, row-major, bit 1 = lit. 16 bytes/row x 64 rows
 * = 1024 bytes per frame. */

const HEX_FRAMES = [
{hex_body}
];

/* Permanent identity + gacha weight, index-aligned with HEX_FRAMES.
 * n is forever; w comes from the manifest rarity (common 1.0 / uncommon 0.5 /
 * rare 0.3 — DAVIES at 0.3 is ~1 in 101 launches over 30 commons). */
export const DAVES = [
{dave_body}
];

export const SPLASH_W = 128;
export const SPLASH_H = 64;
export const SPLASH_COUNT = HEX_FRAMES.length;

/* Decoded once at module load. SPLASH_FRAMES[i] is a Uint8Array of 1024 bytes. */
export const SPLASH_FRAMES = HEX_FRAMES.map(function(hex) {{
    const arr = new Uint8Array(1024);
    for (let i = 0; i < 1024; i++)
        arr[i] = parseInt(hex.substr(i * 2, 2), 16);
    return arr;
}});

/* Back-compat alias: the first frame. */
export const SPLASH_BITS = SPLASH_FRAMES[0];

/* Weighted pick over the pool — same law as the launch-side pickers
 * (pick-splash.py, ensureCustomSplash): totally random WITH repeats, rare
 * Daves marginally rarer (Josh, 2026-08-31). */
export function pickSplashIdx() {{
    let total = 0;
    for (let i = 0; i < DAVES.length; i++) total += DAVES[i].w;
    let r = Math.random() * total;
    for (let i = 0; i < DAVES.length; i++) {{
        r -= DAVES[i].w;
        if (r < 0) return i;
    }}
    return DAVES.length - 1;
}}
""")
print(f'{len(frames)} daves -> {OUT}')
