# Reference-set definitions for research/refs: genre groups, the tag terms that select LMD songs,
# curated artist lists (used against LMD metadata, LAMD text events and freemidi artist pages), and
# era windows. Statistics only: nothing here, and nothing derived from it, carries a note sequence.
#
# Each genre: terms  = Last.fm / Echo Nest tag words (LMD metadata; same evidence rules as
#                      research/lmd/analysis/lmd_select.py)
#             artists = {artist name: era tag}; era tag '80s' (originals, <= 1995) or 'new' (2000s+)
#                       or '' (let the song year decide). An artist listed here is sufficient evidence.
#             era    = (lo, hi) song-year window for TAG evidence (artist evidence is not era-filtered,
#                      the era split uses the year when known)
#             fold   = the public tag this group folds into if it is not its own tag
# Precedence (one genre per song): the first genre in PRECEDENCE that claims the song.

G = {
    # ---- owner-priority styles (deepest sets)
    'darksynth': dict(fold='SYNTHWAVE', era=(2008, 2030), terms=['darksynth', 'dark synth', 'darksynthwave'], artists={
        'Perturbator': 'new', 'Carpenter Brut': 'new', 'Dance With the Dead': 'new', 'Mega Drive': 'new',
        'GOST': 'new', 'Gost': 'new', 'Magic Sword': 'new', 'Daniel Deluxe': 'new', 'Irving Force': 'new',
        'Master Boot Record': 'new', 'Volkor X': 'new', "Tommy '86": 'new', 'Dan Terminus': 'new',
        'Lueur Verte': 'new', 'Hubrid': 'new', 'Kavinsky': '', 'Justice': 'new',
        'John Carpenter': '80s',  # the film-score ancestor, flagged in the write-up
        'Pertubator': 'new', 'Carpenter Brut & Kristoffer Rygg': 'new', 'Hotline Miami': 'new', 'M|O|O|N': 'new',
        'Scattle': 'new', 'Jasper Byrne': 'new', 'El Huervo': 'new', 'Power Glove': 'new', 'Com Truise': 'new'}),
    'synthwave': dict(fold='SYNTHWAVE', era=(2005, 2030), terms=['synthwave', 'retrowave', 'outrun', 'dreamwave',
                                                               'new retro wave', 'chillwave', 'vaporwave'], artists={
        'College': 'new', 'Electric Youth': 'new', 'Mitch Murder': 'new', 'Lazerhawk': 'new',
        'Miami Nights 1984': 'new', 'The Midnight': 'new', 'FM-84': 'new', 'Timecop1983': 'new', 'Gunship': 'new',
        'GUNSHIP': 'new', 'Sunglasses Kid': 'new', 'Waveshaper': 'new', 'Trevor Something': 'new',
        'Ollie Wride': 'new', 'Michael Oakley': 'new', 'Makeup and Vanity Set': 'new', 'Robert Parker': 'new',
        'Tesla Boy': 'new', 'Desire': 'new', 'Chromatics': 'new', 'Kristine': 'new', 'Starcadian': 'new',
        'Kyle Dixon & Michael Stein': 'new', 'S U R V I V E': 'new', 'Survive': 'new', 'Stranger Things': 'new',
        'Scandroid': 'new', 'NINA': 'new', 'LeBrock': 'new', 'Nightcrawler': 'new', 'Droid Bishop': 'new',
        'Mitch Murder & Kalax': 'new', 'Kalax': 'new', 'Big Black Delta': 'new', 'Kavinsky': 'new',
        'Cliff Martinez': 'new', 'Drive': 'new', 'Le Matos': 'new', 'Anoraak': 'new', 'Sally Shapiro': 'new',
        'Valerie': 'new', 'Tokyo Rose': 'new', 'Arcade High': 'new', 'Wice': 'new', 'Jordan F': 'new',
        'Com Truise': 'new', 'Washed Out': 'new', 'Neon Indian': 'new', 'Toro y Moi': 'new', 'M83': 'new',
        'The Weeknd': 'new', 'Duran Duran Duran': 'new', 'Power Glove': 'new', 'Vangelis': '80s',
        'Jan Hammer': '80s', 'Harold Faltermeyer': '80s', 'Tangerine Dream': '80s'}),
    'darkwave': dict(fold='GOTH', era=(1980, 2030), terms=['darkwave', 'dark wave', 'coldwave', 'cold wave',
                                                          'minimal wave', 'ethereal wave', 'neue deutsche todeskunst',
                                                          'minimal synth'], artists={
        'Clan of Xymox': '80s', 'Xmal Deutschland': '80s', 'Asylum Party': '80s', 'Kirlian Camera': '80s',
        'Cocteau Twins': '80s', 'Dead Can Dance': '80s', 'The Frozen Autumn': '', 'Diary of Dreams': '',
        'Black Tape for a Blue Girl': '80s', 'Trisomie 21': '80s', 'Martin Dupont': '80s', 'Die Form': '80s',
        'Deine Lakaien': '', 'Das Ich': '', 'Lacrimosa': '', 'Sopor Aeternus': '', 'Clair Obscur': '80s',
        'Opera Multi Steel': '80s', 'Indochine': '80s', 'Mylène Farmer': '80s', 'Mylene Farmer': '80s',
        'Lebanon Hanover': 'new', 'She Past Away': 'new', 'Boy Harsher': 'new', 'Drab Majesty': 'new',
        'Molchat Doma': 'new', 'Selofan': 'new', 'Cold Cave': 'new', 'Ash Code': 'new', 'Kontravoid': 'new',
        'Minuit Machine': 'new', 'Twin Tribes': 'new', 'Actors': 'new', 'Then Comes Silence': 'new',
        'The KVB': 'new', 'Lust for Youth': 'new', 'Buzz Kull': 'new', 'Hante.': 'new', 'Tempers': 'new',
        'Kælan Mikla': 'new', 'Kaelan Mikla': 'new', 'Riki': 'new', 'The Soft Moon': 'new', 'Light Asylum': 'new',
        'Linea Aspera': 'new', 'Xeno & Oaklander': 'new', 'Automelodi': 'new', 'Former Ghosts': 'new',
        'Soft Kill': 'new', 'Cold Showers': 'new', 'Pink Turns Blue': '80s', 'Principe Valiente': 'new',
        'Sixth June': 'new', 'Qual': 'new', 'Visage': '80s', 'Siouxsie and the Banshees': '80s',
        'The Cure': '80s', 'Depeche Mode': '80s', 'Crystal Castles': 'new', 'Chelsea Wolfe': 'new',
        'IAMX': 'new', 'Hurts': 'new', 'Editors': 'new', 'Wolfsheim': '', 'Camouflage': '80s',
        'De/Vision': '', 'Mesh': '', 'Beborn Beton': ''}),
    'goth': dict(fold='GOTH', era=(1979, 2030), terms=['gothic rock', 'goth rock', 'goth', 'deathrock', 'batcave'],
                 artists={
        'The Sisters of Mercy': '80s', 'Sisters of Mercy': '80s', 'Bauhaus': '80s', 'Siouxsie and the Banshees': '80s',
        'Siouxsie & The Banshees': '80s', 'The Cure': '80s', 'Fields of the Nephilim': '80s', 'The Mission': '80s',
        'The Mission UK': '80s', 'Christian Death': '80s', 'Southern Death Cult': '80s', 'The Cult': '80s',
        'Alien Sex Fiend': '80s', 'Specimen': '80s', 'Love and Rockets': '80s', 'Peter Murphy': '80s',
        'The Damned': '80s', 'Faith and the Muse': 'new', 'London After Midnight': 'new', 'Rosetta Stone': '80s',
        'Red Lorry Yellow Lorry': '80s', 'The March Violets': '80s', 'Skeletal Family': '80s', 'Xymox': '80s',
        'Clan of Xymox': '80s', 'All About Eve': '80s', 'The Danse Society': '80s', 'Play Dead': '80s',
        'Sex Gang Children': '80s', 'UK Decay': '80s', 'Theatre of Hate': '80s', 'The Chameleons': '80s',
        'Killing Joke': '80s', 'Joy Division': '80s', 'Echo & the Bunnymen': '80s', 'Echo and the Bunnymen': '80s',
        'Nick Cave and the Bad Seeds': '', 'The Birthday Party': '80s', 'Tones on Tail': '80s',
        'The Merry Thoughts': '', 'Two Witches': '', 'Inkubus Sukkubus': '', 'Nosferatu': '',
        'Rhombus': '', 'Mephisto Walz': '', 'The Awakening': '', 'Tribe of Gypsies': '',
        'Deathrock': '', 'Twin Tribes': 'new', 'Bestial Mouths': 'new', 'Cemetery Girlz': 'new',
        'Scary Bitches': 'new', 'Aurelio Voltaire': 'new', 'Voltaire': 'new', 'Creature Feature': 'new',
        'The Bolshoi': '80s', 'Gene Loves Jezebel': '80s', 'Lords of the New Church': '80s', 'Ministry': '80s'}),
    'postpunk': dict(fold='POST PUNK', era=(1977, 2030), terms=['post-punk', 'post punk', 'post-punk revival',
                                                               'no wave', 'dance-punk', 'dance punk'], artists={
        'Joy Division': '80s', 'Wire': '80s', 'Gang of Four': '80s', 'Magazine': '80s', 'Public Image Ltd': '80s',
        'Public Image Ltd.': '80s', 'PiL': '80s', 'Echo & the Bunnymen': '80s', 'Echo and the Bunnymen': '80s',
        'Killing Joke': '80s', 'The Chameleons': '80s', 'The Psychedelic Furs': '80s', 'Psychedelic Furs': '80s',
        'The Fall': '80s', 'Television': '80s', 'Siouxsie and the Banshees': '80s', 'The Sound': '80s',
        'The Teardrop Explodes': '80s', 'Comsat Angels': '80s', 'The Comsat Angels': '80s', 'Section 25': '80s',
        'A Certain Ratio': '80s', 'The Durutti Column': '80s', 'Josef K': '80s', 'Orange Juice': '80s',
        'The Pop Group': '80s', 'Delta 5': '80s', 'ESG': '80s', 'Liquid Liquid': '80s', 'Pere Ubu': '80s',
        'Suicide': '80s', 'The Smiths': '80s', 'New Order': '80s', 'Simple Minds': '80s', 'U2': '80s',
        'The Stranglers': '80s', 'Bauhaus': '80s', 'The Cure': '80s', 'Talking Heads': '80s',
        'Interpol': 'new', 'Editors': 'new', 'Bloc Party': 'new', 'Franz Ferdinand': 'new', 'The Rapture': 'new',
        'She Wants Revenge': 'new', 'White Lies': 'new', 'Savages': 'new', 'Protomartyr': 'new',
        'Fontaines D.C.': 'new', 'IDLES': 'new', 'Idles': 'new', 'Shame': 'new', 'Viagra Boys': 'new',
        'Preoccupations': 'new', 'Iceage': 'new', 'Motorama': 'new', 'The Horrors': 'new', 'Liars': 'new',
        'LCD Soundsystem': 'new', '!!!': 'new', 'Radio 4': 'new', 'The Futureheads': 'new', 'Maximo Park': 'new',
        'Maxïmo Park': 'new', 'The Killers': 'new', 'Kasabian': 'new', 'Yeah Yeah Yeahs': 'new',
        'The Strokes': 'new', 'Arctic Monkeys': 'new', 'Kaiser Chiefs': 'new', 'The Bravery': 'new',
        'Black Country, New Road': 'new', 'Squid': 'new', 'Dry Cleaning': 'new', 'Girl Band': 'new',
        'Gilla Band': 'new', 'Omni': 'new', 'Parquet Courts': 'new', 'Ought': 'new', 'Wire Train': '80s',
        'Molchat Doma': 'new', 'Ceremony': 'new', 'Cold Cave': 'new', 'Crystal Stilts': 'new',
        'The National': 'new', 'Placebo': 'new', 'Muse': 'new', 'Hot Hot Heat': 'new', 'Clinic': 'new'}),
    'newwave': dict(fold='NEW WAVE', era=(1976, 2030), terms=['new wave', 'new wave pop', 'new romantic',
                                                             'new wave revival'], artists={
        'Blondie': '80s', 'The Cars': '80s', 'Devo': '80s', 'Talking Heads': '80s', 'The Police': '80s',
        "The B-52's": '80s', 'The B-52s': '80s', 'Duran Duran': '80s', 'Tears for Fears': '80s',
        'Simple Minds': '80s', 'INXS': '80s', 'Missing Persons': '80s', 'A Flock of Seagulls': '80s',
        'Adam Ant': '80s', 'Adam and the Ants': '80s', 'Elvis Costello': '80s', 'XTC': '80s',
        'Men Without Hats': '80s', 'Thompson Twins': '80s', 'Modern English': '80s', 'Squeeze': '80s',
        'The Pretenders': '80s', 'Split Enz': '80s', 'Oingo Boingo': '80s', 'The Fixx': '80s',
        'Spandau Ballet': '80s', 'ABC': '80s', 'Culture Club': '80s', 'Wang Chung': '80s', 'The Motels': '80s',
        'Naked Eyes': '80s', 'Berlin': '80s', 'Til Tuesday': '80s', "'Til Tuesday": '80s', 'Romeo Void': '80s',
        'The Human League': '80s', 'Kajagoogoo': '80s', 'Nena': '80s', 'Falco': '80s', 'Big Country': '80s',
        'The Go-Go\'s': '80s', 'Go-Go\'s': '80s', 'Joe Jackson': '80s', 'Gary Numan': '80s', 'The Vapors': '80s',
        'The Knack': '80s', 'Madness': '80s', 'Echo & the Bunnymen': '80s', 'Icehouse': '80s', 'Real Life': '80s',
        'Animotion': '80s', 'General Public': '80s', 'The Waitresses': '80s', 'The Buggles': '80s',
        'The Killers': 'new', 'The Bravery': 'new', 'Hot Hot Heat': 'new', 'MGMT': 'new', 'Phoenix': 'new',
        'Metronomy': 'new', 'The 1975': 'new', 'Franz Ferdinand': 'new', 'Hurts': 'new', 'Two Door Cinema Club': 'new',
        'Foster the People': 'new', 'Passion Pit': 'new', 'Empire of the Sun': 'new', 'The Naked and Famous': 'new',
        'Walk the Moon': 'new', 'Bastille': 'new', 'St. Lucia': 'new', 'Future Islands': 'new', 'Cut Copy': 'new',
        'Friendly Fires': 'new', 'The Drums': 'new', 'Yeah Yeah Yeahs': 'new', 'The Faint': 'new',
        'Ladytron': 'new', 'Moving Units': 'new', 'Shiny Toy Guns': 'new', 'Mando Diao': 'new'}),
    'synthpop': dict(fold='SYNTHPOP', era=(1978, 2030), terms=['synthpop', 'synth pop', 'synth-pop', 'technopop',
                                                              'electropop', 'futurepop'], artists={
        'Depeche Mode': '80s', 'Pet Shop Boys': '80s', 'Erasure': '80s', 'Orchestral Manoeuvres in the Dark': '80s',
        'OMD': '80s', 'The Human League': '80s', 'Yazoo': '80s', 'Yaz': '80s', 'Soft Cell': '80s',
        'Eurythmics': '80s', 'Heaven 17': '80s', 'Alphaville': '80s', 'a-ha': '80s', 'A-Ha': '80s', 'Visage': '80s',
        'Howard Jones': '80s', 'Kraftwerk': '80s', 'Yello': '80s', 'Ultravox': '80s', 'Bronski Beat': '80s',
        'The Communards': '80s', 'Dead or Alive': '80s', 'Information Society': '80s', 'Camouflage': '80s',
        'Real Life': '80s', 'Nik Kershaw': '80s', 'Book of Love': '80s', 'Anything Box': '80s', 'Cause and Effect': '80s',
        'New Order': '80s', 'Blancmange': '80s', 'China Crisis': '80s', 'Talk Talk': '80s', 'Japan': '80s',
        'Propaganda': '80s', 'Frankie Goes to Hollywood': '80s', 'Wolfsheim': '', 'Mesh': '', 'Covenant': '',
        'Chvrches': 'new', 'CHVRCHES': 'new', 'Ladytron': 'new', 'La Roux': 'new', 'Goldfrapp': 'new', 'Robyn': 'new',
        'Cut Copy': 'new', 'Empire of the Sun': 'new', 'Passion Pit': 'new', 'M83': 'new', 'The Postal Service': 'new',
        'Future Islands': 'new', 'Chromatics': 'new', 'Hurts': 'new', 'Owl City': 'new', 'Years & Years': 'new',
        'Metronomy': 'new', 'Hot Chip': 'new', 'The Knife': 'new', 'Fever Ray': 'new', 'Röyksopp': 'new',
        'Royksopp': 'new', 'Little Boots': 'new', 'Ellie Goulding': 'new', 'Marina and the Diamonds': 'new',
        'Purity Ring': 'new', 'Grimes': 'new', 'Austra': 'new', 'Kavinsky': 'new', 'Parallels': 'new',
        'Electric Youth': 'new', 'Muse': 'new', 'IAMX': 'new', 'VNV Nation': 'new', 'Apoptygma Berzerk': 'new',
        'Iris': 'new', 'Neuroticfish': 'new', 'Assemblage 23': 'new', 'Frozen Plasma': 'new', 'Colony 5': 'new',
        'Seabound': 'new', 'Rotersand': 'new', 'Blutengel': 'new', 'Solar Fake': 'new', 'Namnambulu': 'new'}),
    'italo': dict(fold='ITALO', era=(1977, 2030), terms=['italo disco', 'italo-disco', 'italo', 'hi-nrg', 'hi nrg',
                                                        'euro disco', 'eurodisco', 'italian disco', 'spacesynth'], artists={
        'Gazebo': '80s', 'Ryan Paris': '80s', 'Righeira': '80s', 'Savage': '80s', 'Den Harrow': '80s',
        'Baltimora': '80s', 'Kano': '80s', 'Klein & M.B.O.': '80s', 'Scotch': '80s', 'Fancy': '80s',
        'Laserdance': '80s', 'Koto': '80s', 'Hipnosis': '80s', "Doctor's Cat": '80s', 'Valerie Dore': '80s',
        'P. Lion': '80s', 'Raggio di Luna': '80s', 'Casco': '80s', 'Giorgio Moroder': '80s', 'Change': '80s',
        'Trans-X': '80s', 'Sabrina': '80s', 'Spagna': '80s', 'Albert One': '80s', 'Mike Mareen': '80s',
        'Modern Talking': '80s', 'C.C. Catch': '80s', 'Bad Boys Blue': '80s', 'Silent Circle': '80s',
        'Joy': '80s', 'Lime': '80s', 'Patrick Cowley': '80s', 'Divine': '80s', 'Hazell Dean': '80s',
        'Miquel Brown': '80s', 'Sylvester': '80s', 'Bobby O': '80s', 'Stock Aitken Waterman': '80s',
        'Tom Hooker': '80s', 'Topo & Roby': '80s', 'Sandra': '80s', 'Boney M.': '80s', 'Eddy Huntington': '80s',
        'Radiorama': '80s', 'Mike Francis': '80s', 'Cyber People': '80s', 'Max Him': '80s', 'Brian Ice': '80s',
        'Glass Candy': 'new', 'Italians Do It Better': 'new', 'Desire': 'new', 'Sally Shapiro': 'new',
        'Chromatics': 'new', 'Johnny Jewel': 'new', 'Hot Chip': 'new', 'Tiga': 'new', 'Kalax': 'new'}),
    'ebm': dict(fold='EBM', era=(1980, 2030), terms=['ebm', 'electronic body music', 'electro-industrial',
                                                    'electro industrial', 'aggrotech', 'dark electro', 'industrial dance'],
                artists={
        'Front 242': '80s', 'Nitzer Ebb': '80s', 'DAF': '80s', 'D.A.F.': '80s', 'Deutsch Amerikanische Freundschaft': '80s',
        'Skinny Puppy': '80s', 'Front Line Assembly': '80s', 'Klinik': '80s', 'Die Krupps': '80s',
        'Cabaret Voltaire': '80s', 'Leæther Strip': '80s', 'Leaether Strip': '80s',
        'Pouppée Fabrikk': '80s', 'Laibach': '80s', 'Liaisons Dangereuses': '80s', 'Portion Control': '80s',
        'Signal Aout 42': '80s', 'A Split-Second': '80s', 'Vomito Negro': '80s', 'Borghesia': '80s',
        'Front 242 / Nitzer Ebb': '80s',
        'Covenant': 'new', 'VNV Nation': 'new', 'Combichrist': 'new', 'Suicide Commando': 'new', 'Hocico': 'new',
        'Agonoize': 'new',
        'Frontline Assembly': '80s', 'Wumpscut': 'new', ':Wumpscut:': 'new', 'Feindflug': 'new',
        'Grendel': 'new', 'Nachtmahr': 'new', 'Die Form': '', 'Spetsnaz': 'new', 'Proceed': 'new',
        'Terence Fixmer': 'new', 'Adult.': 'new', 'Youth Code': 'new', 'Author & Punisher': 'new',
        'Boy Harsher': 'new', 'Kontravoid': 'new', 'Schwefelgelb': 'new', 'Das Ich': '', 'Project Pitchfork': '',
        'SITD': 'new', 'Icon of Coil': 'new', 'Assemblage 23': 'new', 'Frozen Plasma': 'new',
        'Apoptygma Berzerk': 'new', 'Funker Vogt': 'new', 'X-RX': 'new', 'Centhron': 'new'}),
    # ---- dance / electronic
    'acid': dict(fold='ACID', era=(1985, 2030), terms=['acid house', 'acid techno', 'acid', 'acid trance'], artists={
        'Phuture': '80s', 'Hardfloor': '', 'Josh Wink': '', 'Wink': '', 'DJ Pierre': '80s', 'Armando': '80s',
        'Adonis': '80s', 'Bam Bam': '80s', 'Fast Eddie': '80s', 'Sleezy D': '80s', 'Tyree': '80s',
        '808 State': '80s', 'A Guy Called Gerald': '80s', 'Humanoid': '80s', 'D-Mob': '80s', 'Lil Louis': '80s',
        'Emmanuel Top': '', 'Plastikman': '', 'Aphex Twin': '', 'Laurent Garnier': '', 'Jesse Saunders': '80s',
        'Maurice': '80s', 'Mr. Fingers': '80s', 'Larry Heard': '80s', 'The Shamen': '80s', 'Bizarre Inc': '80s',
        'Baby Ford': '80s', 'Sterling Void': '80s', 'Mr. Oizo': 'new', 'Chris Liebing': 'new', 'Luke Vibert': 'new',
        'Ceephax Acid Crew': 'new', 'Da Hool': 'new', 'Dave Clarke': '', 'Tin Man': 'new', 'Hardfloor & Josh Wink': ''}),
    'trance': dict(fold='TRANCE', era=(1990, 2030), terms=['trance', 'uplifting trance', 'progressive trance',
                                                          'vocal trance', 'psytrance', 'goa', 'goa trance', 'dream trance',
                                                          'hard trance', 'euro trance'], artists={
        'ATB': '', 'Paul van Dyk': '', 'Tiësto': '', 'Tiesto': '', 'DJ Tiësto': '', 'Armin van Buuren': '',
        'Ferry Corsten': '', 'System F': '', 'Darude': '', 'Robert Miles': '', 'Energy 52': '', 'Chicane': '',
        'Binary Finary': '', 'Gouryella': '', 'Rank 1': '', 'Alice Deejay': '', 'Paul Oakenfold': '',
        'Blank & Jones': '', 'Sash!': '', 'Schiller': '', 'BT': '', 'Above & Beyond': '', 'Ian van Dahl': '',
        'DJ Sammy': '', 'Delerium': '', 'Cosmic Gate': '', 'Push': '', 'Kai Tracid': '', 'Marco V': '',
        'York': '', 'Oliver Lieb': '', 'Mauro Picotto': '', 'Age of Love': '', 'The Age of Love': '',
        'Jam & Spoon': '', 'Dance 2 Trance': '', 'Moby': '', 'Faithless': '', 'Veracocha': '', 'Signum': '',
        'Lange': '', 'Aly & Fila': '', 'Markus Schulz': '', 'Ferry Corsten presents': '', 'Airscape': '',
        'Mario Piu': '', 'Gigi D\'Agostino': '', 'DJ Dado': '', 'Nalin & Kane': '', 'Brainbug': '',
        'Paul Van Dyk': '', 'Vengaboys': '', 'Lasgo': '', 'Kosheen': '', 'Infected Mushroom': '',
        'Astral Projection': '', 'Hallucinogen': '', 'Juno Reactor': '', 'Vini Vici': 'new', 'ATB feat. York': ''}),
    'house': dict(fold='HOUSE', era=(1985, 2030), terms=['house', 'deep house', 'chicago house', 'vocal house',
                                                        'garage house', 'progressive house', 'french house', 'tech house',
                                                        'electro house', 'funky house'], artists={
        'Frankie Knuckles': '80s', 'Marshall Jefferson': '80s', 'Mr. Fingers': '80s', 'Crystal Waters': '',
        'Robin S': '', 'Robin S.': '', 'CeCe Peniston': '', 'Daft Punk': '', 'Stardust': '', 'Modjo': '',
        'Bob Sinclar': '', 'Armand Van Helden': '', 'Basement Jaxx': '', 'Disclosure': 'new', 'Duke Dumont': 'new',
        'Deadmau5': 'new', 'deadmau5': 'new', 'Swedish House Mafia': 'new', 'Eric Prydz': 'new', 'Benny Benassi': '',
        'Todd Terry': '', 'Inner City': '80s', 'Black Box': '', 'Masters at Work': '', 'Kerri Chandler': '',
        'Fisher': 'new', 'Calvin Harris': 'new', 'Joe Smooth': '80s', 'Steve \'Silk\' Hurley': '80s',
        'Farley Jackmaster Funk': '80s', 'Ten City': '80s', 'Kym Mazelle': '80s', 'M/A/R/R/S': '80s',
        'S\'Express': '80s', 'Technotronic': '', 'Snap!': '', 'Cassius': '', 'Alan Braxe': '',
        'Spiller': '', 'Groove Armada': '', 'Junior Jack': '', 'Axwell': 'new', 'Avicii': 'new',
        'David Guetta': 'new', 'Martin Solveig': 'new', 'Stonebridge': '', 'Mousse T.': '', 'Roger Sanchez': '',
        'Kenny Dope': '', 'Moloko': '', 'Everything but the Girl': '', 'Ultra Naté': '', 'Ultra Nate': '',
        'Jaydee': '', 'Chez Damier': '', 'Larry Heard': '80s', 'Lil Louis': '80s', 'Nightcrawlers': '',
        'Kathy Sledge': '', 'Livin\' Joy': '', 'Alcazar': ''}),
    'techno': dict(fold='TECHNO', era=(1987, 2030), terms=['techno', 'detroit techno', 'minimal techno',
                                                          'hard techno', 'tech house', 'schranz'], artists={
        'Jeff Mills': '', 'Derrick May': '', 'Rhythim Is Rhythim': '', 'Juan Atkins': '', 'Model 500': '',
        'Kevin Saunderson': '', 'Underworld': '', 'Orbital': '', 'Plastikman': '', 'Richie Hawtin': '',
        'Laurent Garnier': '', 'Sven Väth': '', 'Westbam': '', 'WestBam': '', 'Paul Kalkbrenner': 'new',
        'Dave Clarke': '', 'Carl Cox': '', 'Adam Beyer': 'new', 'Charlotte de Witte': 'new', 'Marusha': '',
        'U96': '', 'Mayday': '', 'Joey Beltram': '', 'Robert Hood': '', 'Blake Baxter': '', 'Mike Dearborn': '',
        'Speedy J': '', 'Dave Angel': '', 'Luke Slater': '', 'Surgeon': '', 'Ben Sims': '', 'Chris Liebing': 'new',
        'Moby': '', 'The Advent': '', 'Green Velvet': '', 'Cajmere': '', 'Oliver Huntemann': 'new',
        'Moderat': 'new', 'Boris Brejcha': 'new', 'Stephan Bodzin': 'new', 'Anyma': 'new', 'Tale of Us': 'new',
        'Amelie Lens': 'new', 'Len Faki': 'new', 'Ben Klock': 'new', 'Dubfire': 'new', 'Joris Voorn': 'new',
        'Sash': '', 'Scooter': '', 'Mark Spoon': '', 'Hardfloor': '', 'Emmanuel Top': '', 'Mauro Picotto': ''}),
    'electro': dict(fold='ELECTRO', era=(1980, 2030), terms=['electro', 'electro-funk', 'electroclash', 'freestyle',
                                                            'miami bass', 'electro hop'], artists={
        'Kraftwerk': '80s', 'Afrika Bambaataa': '80s', 'Afrika Bambaataa & The Soulsonic Force': '80s',
        'Cybotron': '80s', 'Egyptian Lover': '80s', 'The Egyptian Lover': '80s', "World Class Wreckin' Cru": '80s',
        'Mantronix': '80s', 'Newcleus': '80s', 'Hashim': '80s', 'Twilight 22': '80s', 'Man Parrish': '80s',
        'Drexciya': '', 'Aux 88': '', 'Dopplereffekt': '', 'Arabian Prince': '80s', 'Herbie Hancock': '80s',
        'Jonzun Crew': '80s', 'Whodini': '80s', 'Midnight Star': '80s', 'Zapp': '80s', 'Shannon': '80s',
        'Nu Shooz': '80s', 'Lisa Lisa & Cult Jam': '80s', 'Stevie B': '80s', 'Expose': '80s', 'Exposé': '80s',
        'Information Society': '80s', 'Trans-X': '80s', 'Freeez': '80s', 'Planet Patrol': '80s', 'C-Bank': '80s',
        'Warp 9': '80s', 'Tyrone Brunson': '80s', 'Strafe': '80s', 'Mantronix featuring Wondress': '80s',
        'Miss Kittin': 'new', 'Fischerspooner': 'new', 'Felix da Housecat': 'new', 'Justice': 'new',
        'Boys Noize': 'new', 'Vitalic': 'new', 'Kavinsky': 'new', 'Chromeo': 'new', 'Mr. Oizo': 'new',
        'Adult.': 'new', 'Anthony Rother': 'new', 'Legowelt': 'new', 'The Hacker': 'new', 'Tiga': 'new',
        'Bomfunk MC\'s': '', 'Uncle Jamm\'s Army': '80s', '2 Live Crew': '80s', 'Freestyle': '80s',
        'Magic Mike': '', 'L\'Trimm': '80s', 'Duice': '', 'Ladytron': 'new', 'Crystal Castles': 'new'}),
    'dnb': dict(fold='DNB', era=(1992, 2030), terms=['drum and bass', 'drum n bass', "drum'n'bass", 'liquid funk',
                                                    'neurofunk', 'dnb'], artists={
        'Goldie': '', 'Roni Size': '', 'Roni Size/Reprazent': '', 'Reprazent': '', 'LTJ Bukem': '', 'Photek': '',
        'Pendulum': 'new', 'Chase & Status': 'new', 'Sub Focus': 'new', 'Netsky': 'new', 'DJ Fresh': 'new',
        'Andy C': '', 'High Contrast': 'new', 'Noisia': 'new', 'Aphrodite': '', 'Adam F': '',
        'Grooverider': '', 'Dillinja': '', 'Ed Rush & Optical': '', 'Calibre': 'new', 'London Elektricity': 'new',
        'Rudimental': 'new', 'Wilkinson': 'new', 'Dimension': 'new', 'Kosheen': '', 'M-Beat': '',
        'Hybrid Minds': 'new', 'Camo & Krooked': 'new', 'Pendulum & Fresh': 'new',
        'Sigma': 'new', 'Nu:Tone': 'new', 'Logistics': 'new', 'Brookes Brothers': 'new', 'Culture Shock': 'new',
        'Metrik': 'new', 'Matrix & Futurebound': 'new', 'DJ Zinc': '',
        'Source Direct': '', 'Klute': '',
        'Spor': 'new', 'Feint': 'new', 'Koven': 'new', 'Pola & Bryson': 'new', 'Fred V & Grafix': 'new',
        'Danny Byrd': 'new', 'Hospital Records': 'new', 'The Prototypes': 'new', 'Chase and Status': 'new'}),
    'breaks': dict(fold='BREAKS', era=(1990, 2030), terms=['breakbeat', 'big beat', 'nu skool breaks', 'breaks',
                                                          'florida breaks', 'nu breaks'], artists={
        'The Prodigy': '', 'Prodigy': '', 'The Chemical Brothers': '', 'Chemical Brothers': '', 'Fatboy Slim': '',
        'The Crystal Method': '', 'Crystal Method': '', 'Propellerheads': '', 'Freestylers': '', 'Plump DJs': '',
        'Stanton Warriors': '', 'Adam Freeland': '', 'Hybrid': '', 'Rennie Pilgrem': '', "Bomfunk MC's": '',
        'Lo Fidelity Allstars': '', 'Wiseguys': '', 'The Wiseguys': '', 'Junkie XL': '', 'Leftfield': '',
        'Apollo 440': '', 'Apollo Four Forty': '', 'Bassment Jaxx': '', 'Death in Vegas': '', 'Groove Armada': '',
        'Utah Saints': '', 'The Future Sound of London': '', 'Future Sound of London': '', 'Moby': '',
        'Meat Beat Manifesto': '', 'Deekline & Wizard': '', 'Krafty Kuts': '', 'Hardknox': '', 'Cut La Roc': '',
        'The Dust Brothers': '', 'Norman Cook': '', 'Beats International': '', 'Pitchshifter': '',
        'Pendulum': '', 'Overseer': '', 'Headrillaz': '', 'The Bloody Beetroots': 'new', 'Chemical Brothers, The': ''}),
    'garage': dict(fold='GARAGE', era=(1994, 2030), terms=['uk garage', '2-step', '2 step', 'speed garage',
                                                          'bassline', 'future garage'], artists={
        'Artful Dodger': '', 'Craig David': '', 'MJ Cole': '', 'So Solid Crew': '', 'Wookie': '',
        'Daniel Bedingfield': '', 'Sweet Female Attitude': '', 'Shanks & Bigfoot': '', 'Tina Moore': '',
        'Double 99': '', '187 Lockdown': '', 'Oxide & Neutrino': '', 'DJ Luck & MC Neat': '', 'Ms. Dynamite': '',
        'Ms Dynamite': '', 'Mis-Teeq': '', 'Sunship': '', 'Zed Bias': '', 'Todd Edwards': '', 'Dreem Teem': '',
        'Wideboys': '', 'Disclosure': 'new', 'Burial': 'new', 'Sticky': '', 'The Streets': '', 'Jaimeson': '',
        'Lonyo': '', 'Architechs': '', 'Doolally': '', 'Truesteppers': '', 'Richie Dan': '', 'Kele Le Roc': '',
        'Colour Girl': '', 'Wookie featuring Lain': '', 'Gabrielle': '', 'Mike Skinner': '', 'Kano': 'new',
        'Joel Corry': 'new', 'Sammy Virji': 'new', 'Interplanetary Criminal': 'new', 'Conducta': 'new',
        'Salute': 'new', 'Jorja Smith': 'new', 'Four Tet': 'new', 'Fred again..': 'new', 'Joy Orbison': 'new',
        'Mount Kimbie': 'new', 'Jamie xx': 'new', 'TQD': 'new', 'Groove Chronicles': '', 'El-B': ''}),
    'hardcore': dict(fold='HARDCORE', era=(1990, 2030), terms=['happy hardcore', 'hardcore techno', 'gabber',
                                                              'breakbeat hardcore', 'rave', 'hardstyle', 'uk hardcore',
                                                              'hardcore rave'], artists={
        'Altern-8': '', 'SL2': '', 'Ultra-Sonic': '', 'Hixxy': '', 'Force & Styles': '', 'DJ Paul Elstak': '',
        'Paul Elstak': '', 'Charly Lownoise & Mental Theo': '', 'Rotterdam Termination Source': '', 'Neophyte': '',
        'Dune': '', 'Scooter': '', 'Brisk': '', 'Darren Styles': '', 'Angerfist': 'new', 'Headhunterz': 'new',
        'Showtek': 'new', 'Brennan Heart': 'new', 'The Prodigy': '', 'Liquid': '', 'Acen': '', 'Urban Hype': '',
        'The Smart E\'s': '', 'Smart E\'s': '', 'Human Resource': '', 'Holy Noise': '', '3 Steps Ahead': '',
        'Party Animals': '', 'Technohead': '', 'Sy & Unknown': '', 'Dougal & Gammer': '', 'Gammer': 'new',
        'Wildstylez': 'new', 'Noisecontrollers': 'new', 'D-Block & S-te-Fan': 'new', 'Da Tweekaz': 'new',
        'The Speed Freak': '', 'Thunderdome': '', 'DJ Hixxy': '', 'N-Trance': '', 'Bizarre Inc': '',
        'Q-Tex': '', 'Marusha': '', 'Sash!': '', 'Blümchen': '', 'Blumchen': '', 'Hyper Go-Go': '', 'Awesome 3': ''}),
    'dub': dict(fold='REGGAE', era=(1970, 2030), terms=['dub', 'dub reggae', 'dub techno'], artists={
        'King Tubby': '', 'Lee "Scratch" Perry': '', 'Lee Perry': '', 'Lee Scratch Perry': '', 'Scientist': '',
        'Augustus Pablo': '', 'Mad Professor': '', 'Sly & Robbie': '', 'Sly and Robbie': '', 'Keith Hudson': '',
        'Prince Jammy': '', 'Linton Kwesi Johnson': '', 'Dub Syndicate': '', 'Zion Train': '',
        'Thievery Corporation': '', 'Dreadzone': '', 'Basic Channel': '', 'Rhythm & Sound': '', 'The Upsetters': '',
        'Easy Star All-Stars': 'new', 'Big Youth': '', 'U-Roy': '', 'I-Roy': ''}),
    'reggae': dict(fold='REGGAE', era=(1966, 2030), terms=['reggae', 'roots reggae', 'lovers rock', 'rocksteady',
                                                          'reggae fusion', 'pop reggae'], artists={
        'Bob Marley & The Wailers': '', 'Bob Marley': '', 'Peter Tosh': '', 'Burning Spear': '', 'Steel Pulse': '',
        'UB40': '', 'Israel Vibration': '', 'Culture': '', 'The Abyssinians': '', 'Aswad': '', 'Toots & the Maytals': '',
        'Jimmy Cliff': '', 'Gregory Isaacs': '', 'Dennis Brown': '', 'Third World': '', 'Inner Circle': '',
        'The Congos': '', 'Horace Andy': '', 'Black Uhuru': '', 'Gentleman': 'new', 'Seeed': 'new',
        'Groundation': 'new', 'The Heptones': '', 'Junior Murvin': '', 'Max Romeo': ''}),
    'dancehall': dict(fold='REGGAE', era=(1978, 2030), terms=['dancehall', 'ragga', 'raggamuffin'], artists={
        'Yellowman': '', 'Eek-A-Mouse': '', 'Barrington Levy': '', 'Shabba Ranks': '', 'Beenie Man': '',
        'Bounty Killer': '', 'Sean Paul': 'new', 'Vybz Kartel': 'new', 'Elephant Man': 'new', 'Super Cat': ''}),
    'ska': dict(fold='REGGAE', era=(1960, 2030), terms=['ska', '2 tone', 'two tone', 'ska revival', 'third wave ska'],
                artists={'The Specials': '80s', 'The Selecter': '80s', 'The Beat': '80s', 'Bad Manners': '80s',
                         'The Skatalites': '', 'Prince Buster': '', 'Desmond Dekker': ''}),
    # ---- LATIN (+ reggaeton, salsa, bossa, cumbia), JAZZ (+ swing, bebop, jazz funk), COUNTRY (+ folk, bluegrass)
    'latin': dict(fold='LATIN', era=(1950, 2030), terms=['latin', 'latin pop', 'latin rock', 'tropical', 'merengue',
                                                        'bachata', 'latin jazz', 'tango', 'flamenco', 'rumba',
                                                        'mariachi', 'ranchera', 'latin alternative'], artists={}),
    'reggaeton': dict(fold='LATIN', era=(1995, 2030), terms=['reggaeton', 'latin urban', 'latin hip hop'], artists={}),
    'salsa': dict(fold='LATIN', era=(1950, 2030), terms=['salsa', 'salsa romantica', 'timba', 'mambo', 'cha cha cha',
                                                        'son cubano', 'latin big band'], artists={}),
    'bossa': dict(fold='LATIN', era=(1955, 2030), terms=['bossa nova', 'mpb', 'samba', 'brazilian', 'musica popular brasileira'],
                  artists={}),
    'cumbia': dict(fold='LATIN', era=(1950, 2030), terms=['cumbia', 'vallenato'], artists={}),
    'jazz': dict(fold='JAZZ', era=(1920, 2030), terms=['jazz', 'smooth jazz', 'vocal jazz', 'cool jazz', 'jazz fusion',
                                                      'contemporary jazz', 'modal jazz', 'soul jazz', 'fusion',
                                                      'free jazz', 'jazz vocal', 'jazz piano', 'jazz guitar'], artists={}),
    'swing': dict(fold='JAZZ', era=(1920, 2030), terms=['swing', 'big band', 'jump blues', 'western swing', 'swing revival',
                                                       'electro swing'], artists={}),
    'bebop': dict(fold='JAZZ', era=(1940, 2030), terms=['bebop', 'hard bop', 'post-bop', 'bop'], artists={}),
    'jazzfunk': dict(fold='JAZZ', era=(1965, 2030), terms=['jazz funk', 'jazz-funk', 'acid jazz', 'nu jazz'], artists={}),
    'country': dict(fold='COUNTRY', era=(1945, 2030), terms=['country', 'country rock', 'alt-country', 'outlaw country',
                                                            'honky tonk', 'country pop', 'americana', 'contemporary country',
                                                            'traditional country', 'nashville sound', 'country gospel',
                                                            'texas country', 'red dirt'], artists={}),
    'folk': dict(fold='COUNTRY', era=(1940, 2030), terms=['folk', 'folk rock', 'contemporary folk', 'traditional folk',
                                                         'celtic', 'irish folk', 'folk-rock', 'american folk'], artists={}),
    'bluegrass': dict(fold='COUNTRY', era=(1940, 2030), terms=['bluegrass', 'newgrass', 'progressive bluegrass'], artists={}),
    # ---- more flavours: POP (kpop, jpop, city pop, hyperpop), RNB (neo soul), INDIE (shoegaze, dream pop, grunge),
    #      HIPHOP (trap, lofi, boom bap), DNB (jungle), ROCK (blues)
    'kpop': dict(fold='POP', era=(1995, 2030), terms=['k-pop', 'kpop', 'korean pop'], artists={}),
    'jpop': dict(fold='POP', era=(1985, 2030), terms=['j-pop', 'jpop', 'japanese pop', 'anime', 'j-rock'], artists={}),
    'citypop': dict(fold='POP', era=(1975, 2030), terms=['city pop'], artists={}),
    'hyperpop': dict(fold='POP', era=(2010, 2030), terms=['hyperpop', 'bubblegum bass', 'pc music'], artists={}),
    'neosoul': dict(fold='RNB', era=(1994, 2030), terms=['neo soul', 'neo-soul'], artists={}),
    'shoegaze': dict(fold='INDIE', era=(1985, 2030), terms=['shoegaze', 'shoegazing', 'nu gaze'], artists={}),
    'dreampop': dict(fold='INDIE', era=(1985, 2030), terms=['dream pop', 'ethereal'], artists={}),
    'grunge': dict(fold='INDIE', era=(1987, 2030), terms=['grunge', 'post-grunge'], artists={}),
    'trap': dict(fold='HIPHOP', era=(2003, 2030), terms=['trap', 'crunk', 'dirty south rap', 'southern hip hop',
                                                        'dirty south'], artists={}),
    'lofi': dict(fold='HIPHOP', era=(1995, 2030), terms=['lo-fi hip hop', 'chillhop', 'jazz hop', 'jazzy hip hop',
                                                        'abstract hip hop', 'trip hop', 'instrumental hip hop'], artists={}),
    'boombap': dict(fold='HIPHOP', era=(1985, 2030), terms=['boom bap', 'golden age hip hop', 'east coast rap',
                                                           'east coast hip hop', 'hardcore hip hop', 'old school hip hop'],
                    artists={}),
    'jungle': dict(fold='DNB', era=(1991, 2030), terms=['jungle', 'ragga jungle', 'oldschool jungle'], artists={
        'Congo Natty': '', 'Rebel MC': '', 'Remarc': '', 'M-Beat': '', 'DJ Hype': '', 'Shy FX': '', 'Omni Trio': '',
        'Origin Unknown': ''}),
    'blues': dict(fold='ROCK', era=(1920, 2030), terms=['blues', 'blues rock', 'blues-rock', 'electric blues',
                                                       'chicago blues', 'delta blues', 'texas blues', 'modern blues'],
                  artists={}),
    'ambient': dict(fold='AMBIENT', era=(1970, 2030), terms=['ambient', 'chillout', 'downtempo', 'dark ambient',
                                                            'ambient techno', 'new age', 'space music', 'drone',
                                                            'chill out', 'lounge'], artists={
        'Brian Eno': '', 'Aphex Twin': '', 'The Orb': '', 'Global Communication': '', 'Harold Budd': '',
        'Vangelis': '', 'Jean-Michel Jarre': '', 'Jean Michel Jarre': '', 'Tangerine Dream': '', 'Boards of Canada': '',
        'Enya': '', 'Moby': '', 'Biosphere': '', 'Stars of the Lid': '', 'Hammock': '', 'Air': '', 'Enigma': '',
        'Kitaro': '', 'Klaus Schulze': '', 'Deep Forest': '', 'Delerium': '', 'Future Sound of London': '',
        'The Future Sound of London': '', 'Sigur Rós': '', 'Sigur Ros': '', 'Tycho': 'new', 'Bonobo': 'new',
        'Zero 7': '', 'Morcheeba': '', 'Massive Attack': '', 'Portishead': '', 'Moodswings': '', 'Mike Oldfield': '',
        'William Orbit': '', 'Jon Hopkins': 'new', 'Nils Frahm': 'new', 'Ólafur Arnalds': 'new', 'Max Richter': 'new',
        'Hans Zimmer': 'new', 'Isao Tomita': '', 'Ryuichi Sakamoto': '', 'Café del Mar': '', 'Chicane': '',
        'Lemon Jelly': '', 'Röyksopp': '', 'Royksopp': '', 'Thomas Newman': '', 'Yanni': '', 'Andreas Vollenweider': '',
        'Oliver Shanti': '', 'Suzanne Ciani': '', 'Loscil': 'new', 'Burial': 'new', 'Four Tet': 'new'}),
    # ---- band / song genres (LMD-rich)
    'punk': dict(fold='PUNK', era=(1974, 2030), terms=['punk', 'punk rock', 'pop punk', 'hardcore punk', 'skate punk',
                                                      'oi', 'street punk', '77 punk', 'garage punk', 'melodic hardcore'], artists={
        'Ramones': '80s', 'The Ramones': '80s', 'Sex Pistols': '80s', 'The Clash': '80s', 'Buzzcocks': '80s',
        'Dead Kennedys': '80s', 'Misfits': '80s', 'The Misfits': '80s', 'Black Flag': '80s', 'The Damned': '80s',
        'The Stooges': '80s', 'Iggy Pop': '80s', 'Green Day': 'new', 'The Offspring': 'new', 'Offspring': 'new',
        'Blink-182': 'new', 'blink-182': 'new', 'Bad Religion': '', 'NOFX': '', 'Rancid': '', 'Descendents': '80s',
        'Social Distortion': '', 'Stiff Little Fingers': '80s', 'The Undertones': '80s', 'X': '80s',
        'Minor Threat': '80s', 'Circle Jerks': '80s', 'Sum 41': 'new', 'Pennywise': '', 'Operation Ivy': '80s',
        'Dropkick Murphys': 'new', 'Against Me!': 'new', 'The Vandals': '', 'Bad Brains': '80s', 'Generation X': '80s',
        'The Jam': '80s', 'The Adicts': '80s', 'Sham 69': '80s', 'UK Subs': '80s', 'The Exploited': '80s',
        'Anti-Flag': 'new', 'Rise Against': 'new', 'Alkaline Trio': 'new', 'The Distillers': 'new',
        'Millencolin': 'new', 'Lagwagon': '', 'Face to Face': '', 'MxPx': 'new', 'Good Charlotte': 'new',
        'Simple Plan': 'new', 'New Found Glory': 'new', 'Jimmy Eat World': 'new', 'Fall Out Boy': 'new',
        'My Chemical Romance': 'new', 'The Hives': 'new', 'Die Toten Hosen': '', 'Die Ärzte': '', 'Wizo': '',
        'Turbonegro': 'new', 'Refused': 'new', 'Joyce Manor': 'new', 'IDLES': 'new', 'Amyl and the Sniffers': 'new',
        'The Menzingers': 'new', 'Pup': 'new', 'Title Fight': 'new', 'Descendents ': ''}),
    'rock': dict(fold='ROCK', era=(1960, 2030), terms=['classic rock', 'hard rock', 'rock', 'garage rock', 'blues rock',
                                                      'southern rock', 'album rock', 'arena rock', 'stoner rock',
                                                      'rock and roll', 'soft rock', 'psychedelic rock'], artists={}),
    # ---- added 2026-09-23 (owner): INDIE (+ ALT flavour), METAL, RNB (+ SOUL flavour), INDUSTRIAL flavour
    'alt': dict(fold='INDIE', era=(1985, 2030), terms=['alternative rock', 'alternative',
                                                      'alternative pop rock'], artists={}),
    'indie': dict(fold='INDIE', era=(1985, 2030), terms=['indie rock', 'indie pop', 'indie', 'britpop',
                                                        'lo-fi', 'indie folk', 'noise pop', 'twee pop'],
                  artists={}),
    'metal': dict(fold='METAL', era=(1970, 2030), terms=['heavy metal', 'metal', 'thrash metal', 'nu metal',
                                                        'alternative metal', 'death metal', 'power metal', 'speed metal',
                                                        'glam metal', 'hair metal', 'gothic metal', 'symphonic metal',
                                                        'doom metal', 'black metal', 'progressive metal', 'metalcore',
                                                        'melodic death metal', 'groove metal', 'nwobhm'], artists={}),
    'industrial': dict(fold='DARKSYN', era=(1978, 2030), terms=['industrial', 'industrial rock', 'industrial metal',
                                                               'neue deutsche harte', 'neue deutsche härte', 'noise rock'],
                       artists={
        'Nine Inch Nails': '', 'Ministry': '', 'KMFDM': '', 'Rammstein': 'new', 'Skinny Puppy': '80s',
        'Throbbing Gristle': '80s', 'Einstürzende Neubauten': '80s', 'Einsturzende Neubauten': '80s', 'Godflesh': '',
        'Pigface': '', 'Revolting Cocks': '80s', 'Oomph!': 'new', 'Rob Zombie': 'new', 'White Zombie': '',
        'Filter': '', 'Stabbing Westward': '', 'Gravity Kills': '', 'Static-X': 'new', 'Marilyn Manson': '',
        'Author & Punisher': 'new', 'HEALTH': 'new', '3TEETH': 'new', 'Youth Code': 'new', 'Front Line Assembly': '',
        'Frontline Assembly': '', 'Meat Beat Manifesto': '', 'Chemlab': '', 'My Life With The Thrill Kill Kult': '',
        'Test Dept': '80s', 'Laibach': '', 'Fear Factory': '', 'Die Krupps': '', 'Killing Joke': '',
        'Cabaret Voltaire': '80s', 'Front 242': '80s', 'Mindless Self Indulgence': 'new', 'Celldweller': 'new',
        'Orgy': '', 'Deathstars': 'new', 'Emigrate': 'new', 'Eisbrecher': 'new', 'Megaherz': 'new'}),
    'soul': dict(fold='RNB', era=(1958, 2030), terms=['soul', 'motown', 'northern soul', 'southern soul', 'classic soul',
                                                     'deep soul', 'philly soul', 'soul music', 'memphis soul',
                                                     'blue-eyed soul', 'retro soul'], artists={}),
    'rnb': dict(fold='RNB', era=(1980, 2030), terms=['r&b', 'rnb', 'contemporary r&b', 'new jack swing', 'urban',
                                                    'quiet storm', 'rhythm and blues', 'r and b'], artists={}),
    'disco': dict(fold='DISCO', era=(1974, 2030), terms=['disco', '70s disco', 'nu disco', 'nu-disco', 'post-disco'], artists={
        'Chic': '', 'Donna Summer': '', 'Bee Gees': '', 'Gloria Gaynor': '', 'Sister Sledge': '', 'KC and the Sunshine Band': '',
        'Village People': '', 'Sylvester': '', 'Cerrone': '', 'Giorgio Moroder': '', 'Earth, Wind & Fire': '',
        'Boney M.': '', 'Anita Ward': '', 'Thelma Houston': '', 'Evelyn "Champagne" King': '', 'Candi Staton': '',
        'Chaka Khan': '', 'A Taste of Honey': '', 'Lipps Inc.': '', 'The Trammps': '', 'Tavares': '',
        'Van McCoy': '', 'Amii Stewart': '', 'Patrick Hernandez': '', 'Diana Ross': '', 'Kool & the Gang': '',
        'Dua Lipa': 'new', 'Daft Punk': 'new', 'Jamiroquai': '', 'Purple Disco Machine': 'new', 'Todd Terje': 'new',
        'Breakbot': 'new', 'Lindstrøm': 'new', 'Kylie Minogue': 'new', 'Madonna': 'new', 'Roisin Murphy': 'new'}),
    'funk': dict(fold='FUNK', era=(1965, 2030), terms=['funk', 'p funk', 'p-funk', 'funk rock', 'soul funk',
                                                      'go-go', 'boogie', 'electro-funk'], artists={
        'James Brown': '', 'Parliament': '', 'Funkadelic': '', 'Kool & the Gang': '', 'Earth, Wind & Fire': '',
        'Rick James': '', 'Zapp': '', 'Zapp & Roger': '', 'Cameo': '', 'Ohio Players': '', 'Sly & the Family Stone': '',
        'Tower of Power': '', 'The Meters': '', 'Commodores': '', 'Prince': '', 'George Clinton': '',
        'Bootsy Collins': '', 'The Gap Band': '', 'Rufus': '', 'Brothers Johnson': '', 'The Brothers Johnson': '',
        'Average White Band': '', 'Wild Cherry': '', 'Chic': '', 'Herbie Hancock': '', 'The Time': '',
        'Lakeside': '', 'Slave': '', 'Con Funk Shun': '', 'Mandrill': '', 'War': '', 'Graham Central Station': '',
        'Jamiroquai': '', 'Red Hot Chili Peppers': '', 'Vulfpeck': 'new', 'Bruno Mars': 'new', 'Mark Ronson': 'new',
        'Chromeo': 'new', 'Dam-Funk': 'new', 'Lettuce': 'new', 'The Budos Band': 'new', 'Sharon Jones & The Dap-Kings': 'new'}),
    'hiphop': dict(fold='HIPHOP', era=(1979, 2030), terms=['hip hop', 'rap', 'hip-hop', 'gangsta rap',
                                                          'west coast rap', 'g-funk', 'underground hip hop',
                                                          'pop rap'], artists={}),
    'pop': dict(fold='POP', era=(1980, 2030), terms=['pop', 'dance pop', 'teen pop', 'europop', 'eurodance', 'pop rock',
                                                    'electropop'], artists={}),
}

# One genre per song. Most specific first; the owner-priority groups claim a song before the broad ones.
PRECEDENCE = ['darksynth', 'synthwave', 'darkwave', 'goth', 'ebm', 'industrial', 'italo', 'postpunk', 'synthpop',
              'newwave', 'acid', 'jungle', 'dnb', 'garage', 'hardcore', 'breaks', 'trance', 'techno', 'electro',
              'house', 'dub', 'dancehall', 'ska', 'reggae', 'reggaeton', 'salsa', 'bossa', 'cumbia', 'latin',
              'ambient', 'disco', 'jazzfunk', 'funk', 'neosoul', 'soul', 'trap', 'lofi', 'boombap', 'hiphop', 'rnb',
              'swing', 'bebop', 'jazz', 'bluegrass', 'folk', 'country', 'kpop', 'jpop', 'citypop', 'hyperpop',
              'metal', 'punk', 'shoegaze', 'dreampop', 'grunge', 'alt', 'indie', 'blues', 'rock', 'pop']

# Public styles and the flavours filed under them (owner, 2026-09-23). A flavour is measured as its own
# group; its parent's stats JSON carries it in a 'flavours' block (full targets + deltas from the parent).
# DARKSYN has no songs of its own: it is the union of its three flavours.
PUBLIC = ['house', 'techno', 'trance', 'electro', 'darksyn', 'disco', 'funk', 'dnb', 'breaks', 'hiphop', 'rnb',
          'garage', 'acid', 'reggae', 'ambient', 'hardcore', 'rock', 'indie', 'metal', 'punk', 'newwave', 'italo',
          'pop', 'latin', 'jazz', 'country']
FLAVOUR_OF = {'postpunk': 'newwave', 'goth': 'newwave', 'darkwave': 'newwave', 'synthwave': 'newwave',
              'ebm': 'darksyn', 'industrial': 'darksyn', 'darksynth': 'darksyn',
              'synthpop': 'pop', 'kpop': 'pop', 'jpop': 'pop', 'citypop': 'pop', 'hyperpop': 'pop',
              'soul': 'rnb', 'neosoul': 'rnb', 'alt': 'indie', 'shoegaze': 'indie', 'dreampop': 'indie',
              'grunge': 'indie', 'dub': 'reggae', 'dancehall': 'reggae', 'ska': 'reggae', 'reggaeton': 'latin',
              'salsa': 'latin', 'bossa': 'latin', 'cumbia': 'latin', 'swing': 'jazz', 'bebop': 'jazz',
              'jazzfunk': 'jazz', 'folk': 'country', 'bluegrass': 'country', 'trap': 'hiphop', 'lofi': 'hiphop',
              'boombap': 'hiphop', 'jungle': 'dnb', 'blues': 'rock'}
UNION = {'darksyn': ['ebm', 'industrial', 'darksynth']}

# Soft caps per genre (songs kept, strongest evidence first), and per artist.
CAP_GENRE = {g: 60 for g in G}
CAP_GENRE.update({'darksynth': 120, 'synthwave': 120, 'darkwave': 120, 'goth': 120, 'newwave': 150,
                  'postpunk': 150, 'rock': 150, 'punk': 150, 'synthpop': 120, 'pop': 120, 'disco': 100,
                  'house': 100, 'hiphop': 100, 'funk': 100, 'techno': 100, 'trance': 100, 'italo': 100, 'ebm': 100,
                  'indie': 150, 'alt': 100, 'metal': 150, 'rnb': 150, 'soul': 100, 'industrial': 100,
                  'reggae': 120, 'latin': 150, 'jazz': 150, 'country': 150, 'blues': 100, 'folk': 100})
CAP_ARTIST = 5
CAP_ARTIST_THIN = 8  # genres short of material: darksynth, synthwave, darkwave, acid, garage, dnb, hardcore
THIN = {'darksynth', 'synthwave', 'darkwave', 'acid', 'garage', 'dnb', 'hardcore', 'goth', 'ebm', 'postpunk', 'breaks'}

# freemidi.org artist slugs to fetch for thin groups (checked by hand against the site's artist index;
# only artists the site actually carries are useful).
FREEMIDI = {
    'goth': ['sisters-of-mercy', 'bauhaus', 'cure', 'the-cure', 'siouxsie-and-the-banshees', 'the-mission',
             'fields-of-the-nephilim', 'the-cult', 'cult', 'love-and-rockets', 'peter-murphy', 'christian-death'],
    'postpunk': ['joy-division', 'interpol', 'editors', 'bloc-party', 'franz-ferdinand', 'killing-joke',
                 'echo-and-the-bunnymen', 'psychedelic-furs', 'the-smiths', 'smiths', 'white-lies', 'the-rapture'],
    'newwave': ['the-killers', 'killers', 'blondie', 'the-cars', 'cars', 'devo', 'duran-duran', 'tears-for-fears'],
    'synthwave': ['kavinsky', 'college', 'the-midnight', 'gunship', 'm83', 'chromatics', 'electric-youth'],
    'darksynth': ['perturbator', 'carpenter-brut', 'justice'],
    'darkwave': ['depeche-mode', 'she-past-away', 'molchat-doma', 'lebanon-hanover', 'boy-harsher', 'clan-of-xymox'],
    'ebm': ['front-242', 'nitzer-ebb', 'nine-inch-nails', 'ministry', 'rammstein', 'kmfdm', 'skinny-puppy'],
    'dnb': ['pendulum', 'chase-and-status', 'goldie', 'roni-size', 'rudimental', 'sub-focus', 'netsky'],
    'garage': ['craig-david', 'artful-dodger', 'daniel-bedingfield', 'disclosure', 'the-streets', 'ms-dynamite'],
    'acid': ['phuture', 'hardfloor', 'josh-wink', '808-state'],
    'trance': ['darude', 'atb', 'tiesto', 'robert-miles', 'alice-deejay', 'paul-van-dyk', 'armin-van-buuren'],
    'hardcore': ['scooter', 'dune', 'prodigy'],
    'ambient': ['brian-eno', 'enya', 'enigma', 'vangelis', 'jean-michel-jarre', 'air', 'moby'],
    'acid_extra': [],
}

# An artist listed under several genres counts in exactly ONE (its primary). Keys are normalised names.
PRIMARY = {
    'kavinsky': 'synthwave', 'justice': 'electro', 'power glove': 'darksynth', 'com truise': 'synthwave',
    'electric youth': 'synthwave', 'desire': 'synthwave', 'chromatics': 'synthwave', 'kalax': 'synthwave',
    'sally shapiro': 'italo', 'm83': 'synthpop', 'vangelis': 'ambient', 'tangerine dream': 'ambient',
    'clan of xymox': 'darkwave', 'die form': 'darkwave', 'das ich': 'darkwave', 'boy harsher': 'darkwave',
    'molchat doma': 'darkwave', 'cold cave': 'darkwave', 'kontravoid': 'darkwave', 'twin tribes': 'darkwave',
    'visage': 'synthpop', 'siouxsie and the banshees': 'goth', 'siouxsie the banshees': 'goth', 'the cure': 'postpunk',
    'depeche mode': 'synthpop', 'crystal castles': 'electro', 'iamx': 'darkwave', 'hurts': 'synthpop',
    'editors': 'postpunk', 'wolfsheim': 'darkwave', 'camouflage': 'synthpop', 'mesh': 'synthpop',
    'bauhaus': 'goth', 'the damned': 'punk', 'the chameleons': 'postpunk', 'killing joke': 'postpunk',
    'joy division': 'postpunk', 'echo the bunnymen': 'postpunk', 'echo and the bunnymen': 'postpunk',
    'ministry': 'industrial', 'meat beat manifesto': 'industrial', 'front 242': 'ebm', 'skinny puppy': 'industrial',
    'front line assembly': 'ebm', 'frontline assembly': 'ebm', 'die krupps': 'ebm', 'cabaret voltaire': 'industrial',
    'laibach': 'industrial', 'marilyn manson': 'industrial', 'covenant': 'ebm', 'vnv nation': 'ebm', 'adult': 'electro',
    'assemblage 23': 'ebm', 'frozen plasma': 'ebm', 'apoptygma berzerk': 'ebm', 'kano': 'italo',
    'giorgio moroder': 'disco', 'trans x': 'italo', 'sylvester': 'disco', 'boney m': 'disco', 'hot chip': 'synthpop',
    'tiga': 'electro', 'new order': 'postpunk', 'simple minds': 'newwave', 'talking heads': 'newwave',
    'franz ferdinand': 'postpunk', 'idles': 'postpunk', 'the killers': 'newwave', 'yeah yeah yeahs': 'postpunk',
    'the bravery': 'newwave', 'muse': None, 'hot hot heat': 'postpunk', 'the human league': 'synthpop',
    'kraftwerk': 'electro', 'information society': 'electro', 'real life': 'synthpop', 'ladytron': 'synthpop',
    'cut copy': 'synthpop', 'empire of the sun': 'synthpop', 'passion pit': 'synthpop', 'future islands': 'synthpop',
    'metronomy': 'newwave', 'r yksopp': 'synthpop', 'royksopp': 'synthpop', 'hardfloor': 'acid', 'lil louis': 'house',
    'emmanuel top': 'acid', 'plastikman': 'acid', 'aphex twin': 'ambient', 'laurent garnier': 'techno',
    'mr fingers': 'house', 'larry heard': 'house', 'bizarre inc': 'hardcore', 'mr oizo': 'electro',
    'chris liebing': 'techno', 'dave clarke': 'techno', 'pendulum': 'dnb', 'kosheen': 'dnb', 'disclosure': 'garage',
    'burial': 'garage', 'four tet': 'ambient', 'scooter': 'hardcore', 'the prodigy': 'breaks', 'marusha': 'techno',
    'sash': 'trance', 'bomfunk mc s': 'breaks', 'groove armada': 'house', 'the future sound of london': 'ambient',
    'future sound of london': 'ambient', 'moby': 'ambient', 'chicane': 'trance', 'delerium': 'trance',
    'mauro picotto': 'trance', 'herbie hancock': 'funk', 'zapp': 'funk', 'chromeo': 'funk', 'daft punk': 'house',
    'massive attack': 'ambient', 'chic': 'disco', 'earth wind fire': 'funk', 'kool the gang': 'funk',
    'jamiroquai': 'funk',
}

# TAG evidence (not artist evidence) is refused when one of the artist's top-2 Echo Nest terms is here
# (the metal / garage-rock / dancehall collisions seen in the first selection pass).
METAL = ['gothic metal', 'symphonic metal', 'metal', 'heavy metal', 'nu metal', 'doom metal', 'black metal',
         'death metal', 'power metal', 'alternative metal', 'industrial metal', 'melodic death metal',
         'gothic doom', 'dark metal', 'visual kei', 'neue deutsche harte', 'industrial rock']
EXCL = {'goth': METAL, 'darkwave': METAL, 'postpunk': METAL + ['hip hop', 'rap', 'latin pop', 'easy listening'],
        'ebm': METAL + ['alternative rock', 'post-grunge', 'hard rock'],
        'industrial': ['gothic metal', 'symphonic metal', 'black metal', 'death metal', 'power metal'],
        'rnb': ['hip hop', 'rap', 'gangsta rap'], 'soul': ['hip hop', 'rap'], 'indie': ['hip hop', 'rap'],
        'garage': ['garage rock', 'garage punk', 'psychedelic rock', 'surf music', 'rock', 'blues-rock', 'soul'],
        'dub': ['dancehall', 'ragga', 'reggaeton', 'pop', 'dance pop', 'hip hop'],
        'reggae': ['dancehall', 'ragga', 'reggaeton', 'hip hop', 'dance pop'], 'jazz': ['hip hop', 'rap'],
        'latin': ['hip hop'], 'country': ['hip hop', 'rap'],
        'hardcore': ['eurodance', 'hardcore punk', 'punk'], 'trance': ['hip hop'], 'ambient': ['hard rock', 'rock'],
        'synthwave': METAL, 'darksynth': METAL}
# Genres whose TAG evidence always needs corroboration (every genre except the broad song genres).
STRICT_EXEMPT = {'rock', 'pop', 'hiphop', 'disco', 'funk', 'punk', 'newwave', 'italo', 'synthpop', 'reggae', 'latin',
                 'jazz', 'country', 'soul', 'rnb', 'metal', 'indie', 'alt', 'blues', 'folk', 'swing', 'salsa', 'bossa',
                 'grunge', 'trap', 'boombap', 'ska', 'dancehall', 'bluegrass', 'reggaeton', 'jpop', 'kpop'}

# Manual screen of TAG-selected artists whose evidence is plainly a collision (gothic metal, visual kei,
# alt-rock tagged post-punk). Artist-list evidence is never screened.
SCREEN = {'goth': {'Nightwish', 'THERION', 'Therion', "D'espairs Ray", 'The 69 Eyes', 'THE 69  EYES',
                   'Ville Valo & Natalia Avelon', 'Lovex', 'Héroes del Silencio', 'Evanescence', 'Within Temptation',
                   'HIM', 'Lacuna Coil', 'Cradle Of Filth', 'Theatre Of Tragedy', 'Beseech', 'Moonspell',
                   'AGATHODAIMON', 'Charon', 'TO/DIE/FOR', 'Deathstars', 'Marilyn Manson', 'Nightsky Bequest'},
          'postpunk': {'The Smashing Pumpkins', 'American Hi-Fi', 'Garbage', 'Placebo', 'Vanilla Ice', 'Vikki Carr',
                       'Diamanda Galas', 'Sneaky Sound System', 'Magalie Vaé', 'MPHO', 'Jetzendorfer Hinterhof Musikanten'},
          'ebm': {"D'espairs Ray", 'Jay-Z/ Linkin Park', 'Oneida'},
          'industrial': {'Jay-Z/ Linkin Park', "D'espairs Ray"},
          'dub': {'Skank', 'Pat Travers', 'Bobby McFerrin', 'Loredana Berte', 'Garland Jeffreys',
                  'John Barry_ John Debney - Royal Scottish National Orchestra', 'Sean Paul', 'Sean Kingston',
                  'Shaggy Featuring Rayvon', 'Beenie Man Featuring Janet Jackson'},
          'ambient': {'Foghat', 'David Tao'},
          'garage': {'The Seeds', 'The Barbarians', 'The Gants', 'The Supersuckers', 'Fire', 'Jaheim'},
          'hardcore': {'Corona', 'Chemistry'}}
