# Single-lane drum INGEST candidates from LMD songs (timing + dynamics of ONE drum category per
# phrase - the owner's ruling allows carrying these over; melodic parts are never ingested).
# Usage: python3 lmd_ingest.py <songs.jsonl> <out.json> <out.md> [N per genre/lane]
#
# A candidate is a lane loop found by lmd_measure.lane_loops(): the lane's onset pattern repeats
# exactly with period 1 bar (>= 4 consecutive groove bars) or 2 bars (>= 6 bars). It must have:
#   - REAL dynamics: the song's drums are not flat, >= 3 distinct velocities in the run, and the
#     per-step mean velocities of the loop span >= 15 (an accent shape, not just noise);
#   - >= 2 hits per bar (cymbal lanes >= 1);
# and is labelled 'accented' (mean within-cell velocity SD <= 6: the same accent shape every pass,
# i.e. programmed) or 'humanised' (> 6: a played part whose accents wander).
# Velocities given are the per-step MEANS over the run (the stable accent shape); the first pass's
# raw values are in the JSON. Identical (pattern, velocity-shape) loops are listed once.
import json, sys, collections

TARGET = ['newwave', 'postpunk', 'synthpop', 'italo', 'ebm']
CATS = ['kick', 'snare', 'hat', 'tom', 'perc', 'cymb']
GMN = {35: 'BD2', 36: 'BD', 37: 'rim', 38: 'SD', 39: 'clap', 40: 'eSD', 42: 'CH', 44: 'PH', 46: 'OH', 41: 'T-lf',
       43: 'T-hf', 45: 'T-l', 47: 'T-lm', 48: 'T-hm', 50: 'T-h', 49: 'crash', 57: 'crash2', 55: 'splash', 52: 'china',
       51: 'ride', 59: 'ride2', 53: 'bell', 54: 'tamb', 56: 'cowbell', 69: 'cabasa', 70: 'maracas', 75: 'claves',
       62: 'conga-m', 63: 'conga-o', 64: 'conga-l', 60: 'bongo-h', 61: 'bongo-l', 82: 'shaker', 81: 'tri-o', 80: 'tri-m'}


def main():
    rs = [json.loads(l) for l in open(sys.argv[1])]
    N = int(sys.argv[4]) if len(sys.argv) > 4 else 8
    cands = []
    for r in rs:
        if 'skip' in r or r['genres'][0] not in TARGET or r.get('drum_flat'): continue
        for c, L in (r.get('lanes') or {}).items():
            hits = sum(len(b) for b in L['loop']) / L['period']
            if hits < (1 if c == 'cymb' else 2): continue
            if L['vel_distinct'] < 3 or L['cell_spread'] < 15: continue
            kind = 'accented' if L['cell_sd_mean'] <= 6 else 'humanised'
            bars = []
            for k, b in enumerate(L['loop']):
                steps = {int(i): v for i, v in b.items()}
                pat = ''.join(('o' if c == 'hat' and i in steps and steps[i][1] == 46 else 'x') if i in steps else '.'
                              for i in range(16))
                vel = [round(L['cell_mean'][f'{k}:{i}']) for i in sorted(steps)]
                notes = sorted({GMN.get(v[1], str(v[1])) for v in steps.values()})
                bars.append((pat, vel, notes))
            cands.append({'genre': r['genres'][0], 'lane': c, 'artist': r['artist'], 'title': r['title'], 'tid': r['tid'],
                          'md5': r['md5'], 'bpm': r['bpm'], 'run_bars': L['bars'], 'period': L['period'],
                          'start_bar': L['start_bar'], 'kind': kind, 'cell_spread': L['cell_spread'],
                          'cell_sd_mean': L['cell_sd_mean'], 'bars': bars, 'raw_first_pass': L['loop'],
                          'score': min(L['bars'], 16) * L['cell_spread'] / (1 + L['cell_sd_mean'] / 6)})
    # de-dup identical loops (pattern + velocity shape rounded to 5)
    seen = set(); out = []
    for c in sorted(cands, key=lambda x: -x['score']):
        key = (c['genre'], c['lane'], tuple((p, tuple(5 * round(v / 5) for v in vel)) for p, vel, _ in c['bars']))
        if key in seen: continue
        seen.add(key); out.append(c)
    json.dump(out, open(sys.argv[2], 'w'), indent=0)
    M = ['# LMD single-lane drum ingest candidates', '',
         'Generated by `analysis/lmd_ingest.py` from `analysis/lmd_measure.py` output. **Drums only, one lane per phrase**',
         '(owner ruling: single-lane drum patterns — timing + dynamics — may be carried over). Melodic parts are',
         'statistics only and never appear here. Source: Lakh MIDI Dataset (LMD-matched, CC BY 4.0, Raffel 2016);',
         'cite the dataset and the thesis. Each row names the song the transcription is of so it can be audited and',
         'dropped on request; the MIDI file is `lmd_matched/<tid path>/<md5>.mid`.', '',
         '**Criteria:** the lane\'s onset pattern repeats exactly for ≥ 4 consecutive groove bars (1-bar loop) or ≥ 6',
         '(2-bar loop); the song\'s drums are not flat; ≥ 3 distinct velocities; per-step mean velocities span ≥ 15.',
         '`accented` = the same accent shape every pass (mean within-step SD ≤ 6: programmed); `humanised` = SD > 6',
         '(played; accents wander). Velocities are the per-step MEANS over the run, listed in step order for the `x`/`o`',
         'hits (`o` = open hat). Ranked by run length × accent span, discounted by wander. Identical loops listed once.', '']
    cnt = collections.Counter((c['genre'], c['lane']) for c in out)
    M.append('| genre | ' + ' | '.join(CATS) + ' |'); M.append('|---|' + '---|' * len(CATS))
    for g in TARGET:
        M.append(f'| {g} | ' + ' | '.join(str(cnt[(g, c)]) for c in CATS) + ' |')
    M.append('')
    for g in TARGET:
        M.append(f'## {g}'); M.append('')
        for c in CATS:
            rows = [x for x in out if x['genre'] == g and x['lane'] == c][:N]
            if not rows: continue
            M.append(f'### {g} — {c} ({cnt[(g, c)]} candidates; top {len(rows)})'); M.append('')
            M.append('| song | BPM | run | kind | pattern | velocities (step order) | voices |')
            M.append('|---|---|---|---|---|---|---|')
            for x in rows:
                pat = ' \\| '.join(f'`{p}`' for p, _, _ in x['bars'])
                vel = ' \\| '.join(' '.join(str(v) for v in vel) for _, vel, _ in x['bars'])
                voices = ', '.join(sorted({n for _, _, ns in x['bars'] for n in ns}))
                M.append(f"| {x['artist']} — {x['title'][:40]} | {x['bpm']:.0f} | {x['run_bars']} bars ×{x['period']} | "
                         f"{x['kind']} (span {x['cell_spread']:.0f}, sd {x['cell_sd_mean']:.1f}) | {pat} | {vel} | {voices} |")
            M.append('')
    open(sys.argv[3], 'w').write('\n'.join(M) + '\n')
    print('candidates', len(out), dict(collections.Counter(c['genre'] for c in out)))
    print(dict(collections.Counter((c['genre'], c['kind']) for c in out)))


if __name__ == '__main__': main()
